IF EXISTS(SELECT * FROM sysobjects WHERE name='KK_CheckMeishiData')
   DROP PROCEDURE dbo.KK_CheckMeishiData
GO
CREATE PROC KK_CheckMeishiData
@KAISHA_CD  NVARCHAR(15),                                              --会社コード
@USER_ID    NVARCHAR(30),                                              --ユーザID
@PGM_CD     NVARCHAR(30),                                              --プログラムコード
@SESSION_ID	NVARCHAR(50)											   --セッションID
AS
BEGIN
    SET NOCOUNT ON;
    DECLARE @ERR_MSG_MANDATORY_FIELD    NVARCHAR(20)                               =    '必須項目未設定'
    DECLARE @ERR_MSG_INCORRECT_DATA NVARCHAR(20)                                   =    '入力値不正'
    DECLARE @ERR_MSG_INVALID_NUMBER NVARCHAR(20)                                   =    '数値範囲不正'
    DECLARE @ERR_MSG_INCORRECT_CODE NVARCHAR(20)                                   =    'コード不正'
    DECLARE @ERR_MSG_DUPLICATE_CODE NVARCHAR(20)                                   =    '顧客管理No・対応者コード・日付'
    DECLARE @ERR_MSG_SHUTOKU_DATE_MISITEYI 	NVARCHAR(50)                           =    '取得日が未指定です。CSVファイルの修正または取得日一括設定をしてください。'
    DECLARE @ERR_MSG_SHUTOKU_DATE_KESIKI 	NVARCHAR(50)                           =    '取得日の形式が「yyyy/MM/dd」ではありません。CSVファイルを修正してください。'
    DECLARE @ERR_MSG_KOKYAKU_NM_MISITEYI 	NVARCHAR(50)                           =    '顧客名が未指定です。CSVファイルを修正してください。'
    DECLARE @ERR_MSG_KOKYAKU_NM_FUKUSUU 	NVARCHAR(50)                           =    '該当する顧客が複数あるため自動設定できませんでした。手動で設定してください。'
    DECLARE @ERR_MSG_KOKYAKU_NM_NAYI 		NVARCHAR(50)                           =    '該当する顧客がないため自動設定できませんでした。手動で設定してください。'
    DECLARE @ERR_MSG_AYITETANTOSHA_NM_MISITEYI 	NVARCHAR(50)                       =    '相手先担当者名が未指定です。CSVファイルを修正してください。'
    DECLARE @ERR_MSG_AYITETANTOSHA_NM_FUKUSUU 	NVARCHAR(50)                       =    '該当する相手先担当者が複数あるため自動設定できませんでした。手動で設定してください。'
    DECLARE @ERR_MSG_AYITETANTOSHA_NM_KESIKI 	NVARCHAR(50)                       =    '相手先担当者名が20文字を超えています。CSVファイルを修正してください。'
    DECLARE @ERR_MSG_AYITETANTOSHA_CD_KESIKI 	NVARCHAR(50)                       =    '相手先担当者コードがマスタ値と一致しません。CSVファイルを修正してください。'
    DECLARE @ERR_MSG_TANTOSHA_CD_KESIKI 	NVARCHAR(50)                           =    '担当者コードがマスタ値と一致しません。CSVファイルを修正してください。'
  
    DECLARE @ERR_MSG_YAKUSYOKU	NVARCHAR(50)                                      =    '役職名が５0文字を超えています。CSVファイルを修正してください。'
    DECLARE @ERR_MSG_BUSHONM 	NVARCHAR(50)                                      =    '部署名が５0文字を超えています。CSVファイルを修正してください。'
    DECLARE @ERR_MSG_ZIP_CD 	NVARCHAR(50)                                      =    '郵便番号が７文字を超えています。CSVファイルを修正してください。'
    DECLARE @ERR_MSG_JUSHO1 	NVARCHAR(50)                                      =    '住所が５0文字を超えています。CSVファイルを修正してください。'
    DECLARE @ERR_MSG_TEL 	NVARCHAR(50)                                          =    'TELが13文字を超えています。CSVファイルを修正してください。'
    DECLARE @ERR_MSG_FAX 	NVARCHAR(50)                                          =    'FAXが13文字を超えています。CSVファイルを修正してください。'
    DECLARE @ERR_MSG_MAIL 	NVARCHAR(50)                                          =    'Mailが50文字を超えています。CSVファイルを修正してください。'
    DECLARE @ERR_MSG_MEMO 	NVARCHAR(50)    									  =    'メモが500文字を超えています。CSVファイルを修正してください。'    
	DECLARE @ERR_MSG_KOKYAKUKANRI_NO 	NVARCHAR(50)                              =    '顧客管理NOがマスタ値と一致しません。CSVファイルを修正してください。'
	DECLARE @ERR_MSG_KOKYAKUKANRI_NO_AITESAKI 	NVARCHAR(100)                     =    '設定した顧客管理NOと相手先担当者コードの組合せが正しくありません。CSVファイルを修正してください。'
	DECLARE @ERR_MSG_HOUJIN 	NVARCHAR(100)									  =    '顧客管理NOもしくは相手先担当者コードの顧客管理NOが法人格のため、CSVファイルを修正してください。'
	DECLARE @TOROKUPGM_CD	NVARCHAR(50) = 'CheckMeishiImport'

    --INT変数リターンコード(@RetCd)を初期値0で定義。
    DECLARE @RetCd INT = 0
    --現在日時を変数
    DECLARE @NOW DATETIME = GETDATE()
	DECLARE @COUNT INT = 0	--法人格
	DECLARE @COUNT11 INT = 0		--比較順１
	DECLARE @COUNT12 INT = 0		--比較順１
	DECLARE @COUNT21 INT = 0		--比較順2
	DECLARE @COUNT22 INT = 0		--比較順2
	DECLARE @COUNT3 INT = 0			--比較順3
	DECLARE @COUNT4 INT = 0			--比較順4
	DECLARE @COUNT51 INT = 0		--比較順5
	DECLARE @COUNT52 INT = 0		--比較順5
	DECLARE @COUNT53 INT = 0		--比較順5
	DECLARE @COUNT54 INT = 0		--比較順5
	DECLARE @COUNT55 INT = 0		--比較順5
	DECLARE @COUNT61 INT = 0		--比較順6
	DECLARE @COUNT62 INT = 0		--比較順6
	DECLARE @COUNT63 INT = 0		--比較順6
	DECLARE @COUNT64 INT = 0		--比較順6
	DECLARE @COUNT65 INT = 0		--比較順6
	DECLARE @COUNT66 INT = 0		--比較順6
	DECLARE @COUNTNOCD INT = 0		--顧客管理NOと相手先担当者コードの組合せ
	DECLARE @MAIL NVARCHAR
	DECLARE @KOKYAKU_NM NVARCHAR
	DECLARE @AYITETANTOSHA_NM NVARCHAR
	DECLARE @TEL NVARCHAR
	DECLARE @FAX NVARCHAR
	DECLARE @KOKYAKUKANRI_NO	DECIMAL(10, 0)
	DECLARE @AITESAKI_TANTOSHA_CD	NVARCHAR(30) 
	DECLARE @LINE_NO1	DECIMAL(6, 0)
	DECLARE @KOKYAKUKANRI_NO121	DECIMAL(10, 0) = 0 	--比較順２and比較順1
	DECLARE @KOKYAKUKANRI_NO122	DECIMAL(10, 0) = 0	--比較順２and比較順1
	BEGIN TRY

    --必須チェック
    UPDATE KK_TBL_MEISHI_WK
    SET
    KK_TBL_MEISHI_WK.ERROR_MSG = 
    --顧客名
         CASE WHEN KOKYAKU_NM IS NULL OR KOKYAKU_NM =''
                   THEN @ERR_MSG_KOKYAKU_NM_MISITEYI
    --相手先担当者名
              WHEN AYITETANTOSHA_NM IS NULL OR AYITETANTOSHA_NM = ''
                   THEN @ERR_MSG_AYITETANTOSHA_NM_MISITEYI
    --取得日
              WHEN SHUTOKU_DATE IS NULL OR SHUTOKU_DATE = ''
                   THEN @ERR_MSG_SHUTOKU_DATE_MISITEYI
		END			   
    WHERE KK_TBL_MEISHI_WK.ERROR_MSG IS NULL

	UPDATE KK_TBL_MEISHI_WK
    SET    
	KK_TBL_MEISHI_WK.KOKYAKUKANRI_NO = NULL
	WHERE KK_TBL_MEISHI_WK.KOKYAKUKANRI_NO = 0
	AND  KK_TBL_MEISHI_WK.SESSION_ID = @SESSION_ID
	AND  KK_TBL_MEISHI_WK.KAISHA_CD = @KAISHA_CD
    	
    --日付チェック
    UPDATE KK_TBL_MEISHI_WK
    SET
      KK_TBL_MEISHI_WK.ERROR_MSG = 
           CASE WHEN KK_TBL_MEISHI_WK.SHUTOKU_DATE IS NOT NULL AND ISDATE(KK_TBL_MEISHI_WK.SHUTOKU_DATE) != 1
                     THEN @ERR_MSG_SHUTOKU_DATE_KESIKI  END
    WHERE  KK_TBL_MEISHI_WK.ERROR_MSG IS NULL
		AND KK_TBL_MEISHI_WK.SESSION_ID = @SESSION_ID
		AND  KK_TBL_MEISHI_WK.KAISHA_CD = @KAISHA_CD

	--担当者コード存在チェック 
	UPDATE KK_TBL_MEISHI_WK
    SET
     KK_TBL_MEISHI_WK.ERROR_MSG = 
         CASE WHEN SHAIN.SHAIN_CD IS NULL 
              THEN @ERR_MSG_TANTOSHA_CD_KESIKI ELSE KK_TBL_MEISHI_WK.ERROR_MSG END,			 
	KK_TBL_MEISHI_WK.MEISI_SEQ = SHAIN.SHAIN_CD 
     FROM KK_TBL_MEISHI_WK 
          LEFT JOIN BC_MST_SHAIN AS SHAIN
		--担当者マスタ．会社コード=引数．会社コード 
          ON SHAIN.KAISHA_CD = KK_TBL_MEISHI_WK.KAISHA_CD
		--担当者マスタ.担当者コード=一時テーブル担当者コード
          AND SHAIN.SHAIN_CD = KK_TBL_MEISHI_WK.TANTOSHA_CD
        --担当者マスタ．無効フラグ
          AND SHAIN.MUKOU_FLG = 0
		--担当者マスタ．削除フラグ
		  AND SHAIN.DEL_FLG = 0
    WHERE KK_TBL_MEISHI_WK.ERROR_MSG IS NULL
		  AND  KK_TBL_MEISHI_WK.TANTOSHA_CD IS NOT NULL
		  AND KK_TBL_MEISHI_WK.SESSION_ID = @SESSION_ID
		  AND  KK_TBL_MEISHI_WK.KAISHA_CD = @KAISHA_CD

	--担当者コード未設定の場合
	UPDATE KK_TBL_MEISHI_WK
    SET
     KK_TBL_MEISHI_WK.TANTOSHA_CD = @USER_ID      
    WHERE KK_TBL_MEISHI_WK.ERROR_MSG IS NULL			
		  AND ( KK_TBL_MEISHI_WK.TANTOSHA_CD IS NULL OR KK_TBL_MEISHI_WK.TANTOSHA_CD = '')
		  AND  KK_TBL_MEISHI_WK.SESSION_ID = @SESSION_ID
		  AND  KK_TBL_MEISHI_WK.KAISHA_CD = @KAISHA_CD


	--長さチェック
	--チェック結果を一時テーブルに更新する
    UPDATE KK_TBL_MEISHI_WK
    SET
     KK_TBL_MEISHI_WK.ERROR_MSG =
         CASE WHEN AYITETANTOSHA_NM IS NOT NULL AND LEN(AYITETANTOSHA_NM) > 20
                   THEN @ERR_MSG_AYITETANTOSHA_NM_KESIKI
              WHEN BUSHO_NM IS NOT NULL AND LEN(BUSHO_NM) > 50 
                   THEN @ERR_MSG_BUSHONM
              WHEN YAKUSYOKU IS NOT NULL AND LEN(YAKUSYOKU) > 50
                   THEN @ERR_MSG_YAKUSYOKU
			  --郵便番号はハイフン「-」を除いてカウントする
              WHEN ZIP_CD IS NOT NULL AND LEN(REPLACE(ZIP_CD,'-','')) > 7
                   THEN @ERR_MSG_ZIP_CD 
               WHEN JUSHO IS NOT NULL AND LEN(JUSHO) > 50
                   THEN @ERR_MSG_JUSHO1
              WHEN TEL IS NOT NULL AND LEN(TEL) > 13 
                   THEN @ERR_MSG_TEL
              WHEN FAX IS NOT NULL AND LEN(FAX) > 13
                   THEN @ERR_MSG_FAX
              WHEN EMAIL IS NOT NULL AND LEN(EMAIL) > 50
                   THEN @ERR_MSG_MAIL
              WHEN NAYIYOU IS NOT NULL AND LEN(NAYIYOU) > 500
                   THEN @ERR_MSG_MEMO  
              ELSE KK_TBL_MEISHI_WK.ERROR_MSG
          END
    WHERE
      KK_TBL_MEISHI_WK.ERROR_MSG IS NULL
	  AND KK_TBL_MEISHI_WK.SESSION_ID = @SESSION_ID	
	  AND  KK_TBL_MEISHI_WK.KAISHA_CD = @KAISHA_CD


	--**************** 相手担当者コードAND 顧客管理NO一致チェック**************** 
	UPDATE KK_TBL_MEISHI_WK
    SET    
	KK_TBL_MEISHI_WK.KOKYAKUKANRI_NO =   	
		 CASE WHEN KI.KOKYAKUKANRI_NO IS NULL 
              THEN NULL 
			  ELSE KK_TBL_MEISHI_WK.KOKYAKUKANRI_NO END	, 
	KK_TBL_MEISHI_WK.ERROR_MSG = 
         CASE WHEN KI.KOKYAKUKANRI_NO IS NULL 
              THEN @ERR_MSG_KOKYAKUKANRI_NO 					
			  ELSE KK_TBL_MEISHI_WK.ERROR_MSG END,
	 KK_TBL_MEISHI_WK.MEISI_SEQ = KI.KOKYAKUKANRI_NO 
     FROM KK_TBL_MEISHI_WK 
          LEFT JOIN KK_TBL_KIHONINFO AS KI
		--基本情報．会社コード=引数．会社コード 
          ON KI.KAISHA_CD = KK_TBL_MEISHI_WK.KAISHA_CD
		--基本情報．顧客管理NO=一時テーブル．顧客管理NO
          AND KI.KOKYAKUKANRI_NO = KK_TBL_MEISHI_WK.KOKYAKUKANRI_NO     
		--基本情報．削除フラグ
		  AND KI.DEL_FLG = 0
    WHERE  KK_TBL_MEISHI_WK.ERROR_MSG IS NULL
			AND KK_TBL_MEISHI_WK.KOKYAKUKANRI_NO IS NOT NULL
		  AND KK_TBL_MEISHI_WK.SESSION_ID = @SESSION_ID
		  AND KK_TBL_MEISHI_WK.KAISHA_CD = @KAISHA_CD

	UPDATE KK_TBL_MEISHI_WK
    SET
     KK_TBL_MEISHI_WK.ERROR_MSG = 
         CASE WHEN AITE.AITESAKI_TANTOSHA_CD IS NULL 
              THEN @ERR_MSG_AYITETANTOSHA_CD_KESIKI ELSE KK_TBL_MEISHI_WK.ERROR_MSG END
     FROM KK_TBL_MEISHI_WK 
          LEFT JOIN KK_TBL_AITESAKI_TANTOSHA AS AITE
		--相手先担当者マスタ．会社コード=引数．会社コード 
          ON AITE.KAISHA_CD = KK_TBL_MEISHI_WK.KAISHA_CD
		  --相手先担当者マスタ．相手担当者コード=一時テーブル．相手担当者コード
          AND AITE.AITESAKI_TANTOSHA_CD = KK_TBL_MEISHI_WK.AYITETANTOSHA_CD        
		--相手先担当者マスタ．削除フラグ
		  AND AITE.DEL_FLG = 0
    WHERE  KK_TBL_MEISHI_WK.ERROR_MSG IS NULL
		  AND KK_TBL_MEISHI_WK.AYITETANTOSHA_CD IS NOT NULL
		  AND KK_TBL_MEISHI_WK.SESSION_ID = @SESSION_ID
		  AND KK_TBL_MEISHI_WK.KAISHA_CD = @KAISHA_CD
		   AND KK_TBL_MEISHI_WK.AYITETANTOSHA_CD <>''
		  
	--担当者コードチェックEND************************************************



	--**************** 法人格チェック**************** 
	UPDATE KK_TBL_MEISHI_WK
    SET    
	KK_TBL_MEISHI_WK.ERROR_MSG =  @ERR_MSG_HOUJIN 					
     FROM KK_TBL_MEISHI_WK 
          LEFT JOIN KK_TBL_KIHONINFO AS KI
		--基本情報．会社コード=引数．会社コード 
          ON KI.KAISHA_CD = KK_TBL_MEISHI_WK.KAISHA_CD
		--基本情報．顧客管理NO=一時テーブル．顧客管理NO
          AND KI.KOKYAKUKANRI_NO = KK_TBL_MEISHI_WK.KOKYAKUKANRI_NO     
		--基本情報．削除フラグ
		  AND KI.DEL_FLG = 0
    WHERE  KK_TBL_MEISHI_WK.ERROR_MSG IS NULL
		　AND KK_TBL_MEISHI_WK.KOKYAKUKANRI_NO IS NOT NULL
		  AND KK_TBL_MEISHI_WK.SESSION_ID = @SESSION_ID
		  AND KK_TBL_MEISHI_WK.KAISHA_CD = @KAISHA_CD
		  AND KI.OYA_KOKYAKUKANRI_NO IS NULL
		  AND (KI.TORIHIKISAKI_CD IS NULL OR KI.TORIHIKISAKI_CD ='')


	UPDATE KK_TBL_MEISHI_WK
    SET    
	KK_TBL_MEISHI_WK.ERROR_MSG =  @ERR_MSG_HOUJIN	 					
     FROM KK_TBL_MEISHI_WK
	 LEFT JOIN KK_TBL_AITESAKI_TANTOSHA AS AITE
		--相手先担当者マスタ．会社コード=引数．会社コード 
          ON AITE.KAISHA_CD = KK_TBL_MEISHI_WK.KAISHA_CD
		 --相手先担当者マスタ．相手担当者コード=一時テーブル．相手担当者コード
          AND AITE.AITESAKI_TANTOSHA_CD = KK_TBL_MEISHI_WK.AYITETANTOSHA_CD        
		--相手先担当者マスタ．削除フラグ
		  AND AITE.DEL_FLG = 0
    INNER JOIN KK_TBL_KIHONINFO AS KI
		--基本情報．会社コード=引数．会社コード 
          ON KI.KAISHA_CD = AITE.KAISHA_CD
		--基本情報．顧客管理NO=一時テーブル．顧客管理NO
          AND KI.KOKYAKUKANRI_NO = AITE.KOKYAKUKANRI_NO     
		--基本情報．削除フラグ
		  AND KI.DEL_FLG = 0
    WHERE  KK_TBL_MEISHI_WK.ERROR_MSG IS NULL
		　AND KK_TBL_MEISHI_WK.AYITETANTOSHA_CD IS NOT NULL
		  AND KK_TBL_MEISHI_WK.AYITETANTOSHA_CD <> ''
		  AND KK_TBL_MEISHI_WK.SESSION_ID = @SESSION_ID
		  AND KK_TBL_MEISHI_WK.KAISHA_CD = @KAISHA_CD
		  AND KI.OYA_KOKYAKUKANRI_NO IS NULL
		  AND (KI.TORIHIKISAKI_CD IS NULL OR KI.TORIHIKISAKI_CD ='')

	--**************** 法人格一致チェックEND**************** 

	DECLARE CUR_SHITE CURSOR LOCAL FOR
	SELECT 
	   KOKYAKUKANRI_NO													   --顧客管理NO
       ,AYITETANTOSHA_CD                                                   --相手担当者コード
	   ,LINE_NO
	FROM
		KK_TBL_MEISHI_WK
	WHERE
		KK_TBL_MEISHI_WK.KAISHA_CD = @KAISHA_CD
		AND
		KK_TBL_MEISHI_WK.SESSION_ID = @SESSION_ID
		AND
		KK_TBL_MEISHI_WK.ERROR_MSG IS NULL
		AND
		(KK_TBL_MEISHI_WK.KOKYAKUKANRI_NO IS NOT NULL OR KK_TBL_MEISHI_WK.AYITETANTOSHA_CD IS NOT NULL OR KK_TBL_MEISHI_WK.AYITETANTOSHA_CD <>'')
		AND
		@PGM_CD <> @TOROKUPGM_CD

	OPEN CUR_SHITE		
	FETCH NEXT FROM CUR_SHITE
		INTO @KOKYAKUKANRI_NO	
			,@AITESAKI_TANTOSHA_CD 
			,@LINE_NO1 
	WHILE @@FETCH_STATUS = 0
	BEGIN			
		IF @KOKYAKUKANRI_NO IS NOT NULL  AND  (@AITESAKI_TANTOSHA_CD ='' OR @AITESAKI_TANTOSHA_CD IS NULL)  BEGIN 
			SELECT 
			@COUNT11 = COUNT(AITE.KOKYAKUKANRI_NO),
			@COUNT12 = COUNT(AITE.AITESAKI_TANTOSHA_CD)
			FROM KK_TBL_MEISHI_WK
			LEFT JOIN KK_TBL_AITESAKI_TANTOSHA AITE
			ON AITE.KAISHA_CD = KK_TBL_MEISHI_WK.KAISHA_CD
			AND AITE.KOKYAKUKANRI_NO = KK_TBL_MEISHI_WK.KOKYAKUKANRI_NO
			AND REPLACE(AITE.MAIL,' ','') = REPLACE(KK_TBL_MEISHI_WK.EMAIL,' ','') COLLATE Japanese_CI_AS_KS
			AND AITE.DEL_FLG = 0
			INNER JOIN KK_TBL_KIHONINFO AS KI
			--基本情報．会社コード=引数．会社コード 
		       ON KI.KAISHA_CD = AITE.KAISHA_CD
			--基本情報．顧客管理NO=一時テーブル．顧客管理NO
		       AND KI.KOKYAKUKANRI_NO = AITE.KOKYAKUKANRI_NO     
			--基本情報．削除フラグ
			AND KI.DEL_FLG = 0
			WHERE  KK_TBL_MEISHI_WK.SESSION_ID = @SESSION_ID
				AND KK_TBL_MEISHI_WK.KAISHA_CD = @KAISHA_CD
				AND KK_TBL_MEISHI_WK.LINE_NO = @LINE_NO1
				AND KK_TBL_MEISHI_WK.EMAIL IS NOT NULL
				AND AITE.KOKYAKUKANRI_NO = @KOKYAKUKANRI_NO

			IF @COUNT11 =1 AND @COUNT12 =1 BEGIN	   --比較順１	
				UPDATE KK_TBL_MEISHI_WK SET 
				KK_TBL_MEISHI_WK.KOKYAKUKANRI_NO = AITE.KOKYAKUKANRI_NO,
				KK_TBL_MEISHI_WK.AYITETANTOSHA_CD = AITE.AITESAKI_TANTOSHA_CD
				FROM KK_TBL_MEISHI_WK
				LEFT JOIN KK_TBL_AITESAKI_TANTOSHA AITE
				ON AITE.KAISHA_CD = KK_TBL_MEISHI_WK.KAISHA_CD
				AND REPLACE(AITE.MAIL,' ','') = REPLACE(KK_TBL_MEISHI_WK.EMAIL,' ','') COLLATE Japanese_CI_AS_KS
				AND AITE.MAIL IS NOT NULL
				AND AITE.DEL_FLG = 0
				WHERE  KK_TBL_MEISHI_WK.SESSION_ID = @SESSION_ID
				AND KK_TBL_MEISHI_WK.KAISHA_CD = @KAISHA_CD
				AND KK_TBL_MEISHI_WK.LINE_NO = @LINE_NO1
				AND AITE.KOKYAKUKANRI_NO = @KOKYAKUKANRI_NO
			END
			ELSE BEGIN
					SELECT 
					@COUNT21 = COUNT(AITE.KOKYAKUKANRI_NO),
					@COUNT22 = COUNT(AITE.AITESAKI_TANTOSHA_CD)
					FROM KK_TBL_MEISHI_WK
					LEFT JOIN KK_TBL_AITESAKI_TANTOSHA AITE
					ON AITE.KAISHA_CD = KK_TBL_MEISHI_WK.KAISHA_CD
					AND AITE.KOKYAKUKANRI_NO = KK_TBL_MEISHI_WK.KOKYAKUKANRI_NO
					AND REPLACE(AITE.AITESAKI_TANTOSHA_NM,' ','') = REPLACE(KK_TBL_MEISHI_WK.AYITETANTOSHA_NM,' ','') COLLATE Japanese_CI_AS_KS
					AND REPLACE(AITE.KOKYAKU_NM,' ','') = REPLACE(KK_TBL_MEISHI_WK.KOKYAKU_NM,' ','') COLLATE Japanese_CI_AS_KS
					AND AITE.DEL_FLG = 0
					INNER JOIN KK_TBL_KIHONINFO AS KI
					--基本情報．会社コード=引数．会社コード 
					ON KI.KAISHA_CD = AITE.KAISHA_CD
					--基本情報．顧客管理NO=一時テーブル．顧客管理NO
					AND KI.KOKYAKUKANRI_NO = AITE.KOKYAKUKANRI_NO     
					--基本情報．削除フラグ
					AND KI.DEL_FLG = 0
					WHERE  KK_TBL_MEISHI_WK.SESSION_ID = @SESSION_ID
						AND KK_TBL_MEISHI_WK.KAISHA_CD = @KAISHA_CD
						AND KK_TBL_MEISHI_WK.LINE_NO = @LINE_NO1
						AND AITE.KOKYAKUKANRI_NO = @KOKYAKUKANRI_NO
						AND AITE.KOKYAKU_NM IS NOT NULL 
						AND AITE.AITESAKI_TANTOSHA_NM <> '' 
					IF @COUNT21 =1 AND @COUNT22 =1 BEGIN			---比較順２
						UPDATE KK_TBL_MEISHI_WK SET 
						KK_TBL_MEISHI_WK.KOKYAKUKANRI_NO = AITE.KOKYAKUKANRI_NO,
						KK_TBL_MEISHI_WK.AYITETANTOSHA_CD = AITE.AITESAKI_TANTOSHA_CD		
						FROM KK_TBL_MEISHI_WK
						LEFT JOIN KK_TBL_AITESAKI_TANTOSHA AITE
						ON AITE.KAISHA_CD = KK_TBL_MEISHI_WK.KAISHA_CD
						AND REPLACE(AITE.AITESAKI_TANTOSHA_NM,' ','') = REPLACE(KK_TBL_MEISHI_WK.AYITETANTOSHA_NM,' ','') COLLATE Japanese_CI_AS_KS
						AND REPLACE(AITE.KOKYAKU_NM,' ','') = REPLACE(KK_TBL_MEISHI_WK.KOKYAKU_NM,' ','') COLLATE Japanese_CI_AS_KS
						AND AITE.DEL_FLG = 0
						INNER JOIN KK_TBL_KIHONINFO AS KI
						--基本情報．会社コード=引数．会社コード 
						ON KI.KAISHA_CD = AITE.KAISHA_CD
						--基本情報．顧客管理NO=一時テーブル．顧客管理NO
						AND KI.KOKYAKUKANRI_NO = AITE.KOKYAKUKANRI_NO     
						--基本情報．削除フラグ
						AND KI.DEL_FLG = 0
						WHERE  KK_TBL_MEISHI_WK.SESSION_ID = @SESSION_ID
						AND KK_TBL_MEISHI_WK.KAISHA_CD = @KAISHA_CD
						AND KK_TBL_MEISHI_WK.LINE_NO = @LINE_NO1
						AND AITE.KOKYAKUKANRI_NO = @KOKYAKUKANRI_NO
						AND AITE.KOKYAKU_NM IS NOT NULL 
						AND AITE.AITESAKI_TANTOSHA_NM <> '' 
					END
					ELSE IF @COUNT12 > 1 OR @COUNT22 > 1  BEGIN
							UPDATE KK_TBL_MEISHI_WK SET 
							KK_TBL_MEISHI_WK.ERROR_MSG = @ERR_MSG_AYITETANTOSHA_NM_FUKUSUU
							FROM KK_TBL_MEISHI_WK							
							WHERE  KK_TBL_MEISHI_WK.SESSION_ID = @SESSION_ID
							AND KK_TBL_MEISHI_WK.KAISHA_CD = @KAISHA_CD
							AND KK_TBL_MEISHI_WK.LINE_NO = @LINE_NO1
					END							
			END
		END
			
		IF @KOKYAKUKANRI_NO IS NULL  AND @AITESAKI_TANTOSHA_CD <> '' AND @AITESAKI_TANTOSHA_CD IS NOT NULL  BEGIN 
					UPDATE KK_TBL_MEISHI_WK SET	
					KK_TBL_MEISHI_WK.KOKYAKUKANRI_NO = AITE.KOKYAKUKANRI_NO				
					FROM KK_TBL_MEISHI_WK			
					LEFT JOIN KK_TBL_AITESAKI_TANTOSHA AS AITE
					--相手先担当者マスタ．会社コード=引数．会社コード 
					ON AITE.KAISHA_CD = KK_TBL_MEISHI_WK.KAISHA_CD
					--相手先担当者マスタ．相手担当者コード=一時テーブル．相手担当者コード
					AND AITE.AITESAKI_TANTOSHA_CD = @AITESAKI_TANTOSHA_CD         
					--相手先担当者マスタ．削除フラグ
					AND AITE.DEL_FLG = 0
					WHERE KK_TBL_MEISHI_WK.SESSION_ID = @SESSION_ID
					AND KK_TBL_MEISHI_WK.KAISHA_CD = @KAISHA_CD
					AND KK_TBL_MEISHI_WK.LINE_NO = @LINE_NO1
			END
		IF @KOKYAKUKANRI_NO IS NOT NULL AND @AITESAKI_TANTOSHA_CD IS NOT NULL AND @AITESAKI_TANTOSHA_CD <> '' BEGIN 
			SELECT
			@COUNTNOCD = COUNT(AITE.KOKYAKUKANRI_NO)
			FROM
			KK_TBL_AITESAKI_TANTOSHA AITE
			WHERE
			AITE.KAISHA_CD = @KAISHA_CD
			AND
			AITE.KOKYAKUKANRI_NO = @KOKYAKUKANRI_NO
			AND
			AITE.AITESAKI_TANTOSHA_CD = @AITESAKI_TANTOSHA_CD
			IF @COUNTNOCD = 0 BEGIN
				UPDATE KK_TBL_MEISHI_WK SET	
				KK_TBL_MEISHI_WK.ERROR_MSG = @ERR_MSG_KOKYAKUKANRI_NO_AITESAKI				
				FROM KK_TBL_MEISHI_WK	
				WHERE KK_TBL_MEISHI_WK.SESSION_ID = @SESSION_ID
				AND KK_TBL_MEISHI_WK.KAISHA_CD = @KAISHA_CD
				AND KK_TBL_MEISHI_WK.LINE_NO = @LINE_NO1

			END
		END
	FETCH NEXT FROM CUR_SHITE
	INTO @KOKYAKUKANRI_NO	
		,@AITESAKI_TANTOSHA_CD 
		,@LINE_NO1 
	END
	--カーソルを開放する
	CLOSE CUR_SHITE
	DEALLOCATE CUR_SHITE


	--*****************マッチング処理START**************************************************
	--カーソル マッチング
	DECLARE  @LINE_NO		DECIMAL(6)                                                                                 
    DECLARE  @ERROR_MSG	NVARCHAR(100)                                                                          
                                
	
	DECLARE CUR_MEISHI CURSOR LOCAL FOR
	SELECT 
	   LINE_NO														--(付加情報)ファイル行番号
       ,ERROR_MSG                                                   --(付加情報)エラー内容
	FROM
		KK_TBL_MEISHI_WK
	WHERE
		KK_TBL_MEISHI_WK.KAISHA_CD = @KAISHA_CD
		AND
		KK_TBL_MEISHI_WK.SESSION_ID = @SESSION_ID
		AND
		KK_TBL_MEISHI_WK.ERROR_MSG IS NULL
		AND
		KK_TBL_MEISHI_WK.KOKYAKUKANRI_NO IS NULL
		AND
		@PGM_CD <> @TOROKUPGM_CD

	OPEN CUR_MEISHI		
	FETCH NEXT FROM CUR_MEISHI
		INTO @LINE_NO	
			,@ERROR_MSG  
	WHILE @@FETCH_STATUS = 0
	BEGIN	
		
		SELECT 
		@COUNT11 = COUNT(AITE.KOKYAKUKANRI_NO),
		@COUNT12 = COUNT(AITE.AITESAKI_TANTOSHA_CD)
		FROM KK_TBL_MEISHI_WK
		LEFT JOIN KK_TBL_AITESAKI_TANTOSHA AITE
		ON AITE.KAISHA_CD = KK_TBL_MEISHI_WK.KAISHA_CD
		AND REPLACE(AITE.MAIL,' ','') = REPLACE(KK_TBL_MEISHI_WK.EMAIL,' ','') COLLATE Japanese_CI_AS_KS
		AND AITE.DEL_FLG = 0
		INNER JOIN KK_TBL_KIHONINFO AS KI
		--基本情報．会社コード=引数．会社コード 
        ON KI.KAISHA_CD = AITE.KAISHA_CD
		--基本情報．顧客管理NO=一時テーブル．顧客管理NO
        AND KI.KOKYAKUKANRI_NO = AITE.KOKYAKUKANRI_NO     
		--基本情報．削除フラグ
		AND KI.DEL_FLG = 0
		WHERE KK_TBL_MEISHI_WK.SESSION_ID = @SESSION_ID
			AND KK_TBL_MEISHI_WK.KAISHA_CD = @KAISHA_CD
			AND KK_TBL_MEISHI_WK.EMAIL IS NOT NULL 
			AND KK_TBL_MEISHI_WK.LINE_NO = @LINE_NO
			AND KI.OYA_KOKYAKUKANRI_NO IS NOT NULL

		IF @COUNT11 =1 AND @COUNT12 =1 BEGIN	   --比較順１	
			UPDATE KK_TBL_MEISHI_WK SET 
			KK_TBL_MEISHI_WK.KOKYAKUKANRI_NO = AITE.KOKYAKUKANRI_NO,
			KK_TBL_MEISHI_WK.AYITETANTOSHA_CD = AITE.AITESAKI_TANTOSHA_CD
			FROM KK_TBL_MEISHI_WK
			LEFT JOIN KK_TBL_AITESAKI_TANTOSHA AITE
			ON AITE.KAISHA_CD = KK_TBL_MEISHI_WK.KAISHA_CD
			AND REPLACE(AITE.MAIL,' ','') = REPLACE(KK_TBL_MEISHI_WK.EMAIL,' ','') COLLATE Japanese_CI_AS_KS
			AND AITE.MAIL IS NOT NULL
			AND AITE.DEL_FLG = 0
			WHERE KK_TBL_MEISHI_WK.SESSION_ID = @SESSION_ID
			AND KK_TBL_MEISHI_WK.KAISHA_CD = @KAISHA_CD
			AND KK_TBL_MEISHI_WK.LINE_NO = @LINE_NO	
		END
		ELSE BEGIN
			SELECT 
			@COUNT21 = COUNT(AITE.KOKYAKUKANRI_NO),
			@COUNT22 = COUNT(AITE.AITESAKI_TANTOSHA_CD)
			FROM KK_TBL_MEISHI_WK
			LEFT JOIN KK_TBL_AITESAKI_TANTOSHA AITE
			ON AITE.KAISHA_CD = KK_TBL_MEISHI_WK.KAISHA_CD
			AND REPLACE(AITE.AITESAKI_TANTOSHA_NM,' ','') = REPLACE(KK_TBL_MEISHI_WK.AYITETANTOSHA_NM,' ','')  COLLATE Japanese_CI_AS_KS
			AND REPLACE(AITE.KOKYAKU_NM,' ','') = REPLACE(KK_TBL_MEISHI_WK.KOKYAKU_NM,' ','')  COLLATE Japanese_CI_AS_KS
			AND AITE.DEL_FLG = 0
			INNER JOIN KK_TBL_KIHONINFO AS KI
			--基本情報．会社コード=引数．会社コード 
			ON KI.KAISHA_CD = AITE.KAISHA_CD
			--基本情報．顧客管理NO=一時テーブル．顧客管理NO
			AND KI.KOKYAKUKANRI_NO = AITE.KOKYAKUKANRI_NO     
			--基本情報．削除フラグ
			AND KI.DEL_FLG = 0
			WHERE KK_TBL_MEISHI_WK.SESSION_ID = @SESSION_ID
				AND KK_TBL_MEISHI_WK.KAISHA_CD = @KAISHA_CD
				AND KK_TBL_MEISHI_WK.KOKYAKU_NM IS NOT NULL
				AND KK_TBL_MEISHI_WK.AYITETANTOSHA_NM IS NOT NULL
				AND KK_TBL_MEISHI_WK.LINE_NO = @LINE_NO
				AND KI.OYA_KOKYAKUKANRI_NO IS NOT NULL
			IF @COUNT21 =1 AND @COUNT22 =1 BEGIN			---比較順２
				UPDATE KK_TBL_MEISHI_WK SET 
				KK_TBL_MEISHI_WK.KOKYAKUKANRI_NO = AITE.KOKYAKUKANRI_NO,
				KK_TBL_MEISHI_WK.AYITETANTOSHA_CD = AITE.AITESAKI_TANTOSHA_CD		
				FROM KK_TBL_MEISHI_WK
				LEFT JOIN KK_TBL_AITESAKI_TANTOSHA AITE
				ON AITE.KAISHA_CD = KK_TBL_MEISHI_WK.KAISHA_CD
				AND REPLACE(AITE.AITESAKI_TANTOSHA_NM,' ','') = REPLACE(KK_TBL_MEISHI_WK.AYITETANTOSHA_NM,' ','') COLLATE Japanese_CI_AS_KS
				AND REPLACE(AITE.KOKYAKU_NM,' ','') = REPLACE(KK_TBL_MEISHI_WK.KOKYAKU_NM,' ','')  COLLATE Japanese_CI_AS_KS
				AND AITE.DEL_FLG = 0
				WHERE KK_TBL_MEISHI_WK.SESSION_ID = @SESSION_ID
				AND KK_TBL_MEISHI_WK.KAISHA_CD = @KAISHA_CD
				AND KK_TBL_MEISHI_WK.LINE_NO = @LINE_NO
			END
			ELSE BEGIN
					SELECT 
					@COUNT11 = COUNT(DISTINCT AITE.KOKYAKUKANRI_NO)			
					FROM KK_TBL_MEISHI_WK
					LEFT JOIN KK_TBL_AITESAKI_TANTOSHA AITE
					ON AITE.KAISHA_CD = KK_TBL_MEISHI_WK.KAISHA_CD
					AND REPLACE(AITE.MAIL,' ','') = REPLACE(KK_TBL_MEISHI_WK.EMAIL,' ','') COLLATE Japanese_CI_AS_KS
					AND AITE.DEL_FLG = 0
					INNER JOIN KK_TBL_KIHONINFO AS KI
					--基本情報．会社コード=引数．会社コード 
					ON KI.KAISHA_CD = AITE.KAISHA_CD
					--基本情報．顧客管理NO=一時テーブル．顧客管理NO
					AND KI.KOKYAKUKANRI_NO = AITE.KOKYAKUKANRI_NO     
					--基本情報．削除フラグ
					AND KI.DEL_FLG = 0
					WHERE KK_TBL_MEISHI_WK.SESSION_ID = @SESSION_ID
						AND KK_TBL_MEISHI_WK.KAISHA_CD = @KAISHA_CD
						AND KK_TBL_MEISHI_WK.EMAIL IS NOT NULL 
						AND KK_TBL_MEISHI_WK.LINE_NO = @LINE_NO
						AND KI.OYA_KOKYAKUKANRI_NO IS NOT NULL
					
					SELECT 
					@COUNT21 = COUNT(DISTINCT AITE.KOKYAKUKANRI_NO)
					FROM KK_TBL_MEISHI_WK
					LEFT JOIN KK_TBL_AITESAKI_TANTOSHA AITE
					ON AITE.KAISHA_CD = KK_TBL_MEISHI_WK.KAISHA_CD
					AND REPLACE(AITE.AITESAKI_TANTOSHA_NM,' ','') = REPLACE(KK_TBL_MEISHI_WK.AYITETANTOSHA_NM,' ','') COLLATE Japanese_CI_AS_KS
					AND REPLACE(AITE.KOKYAKU_NM,' ','') = REPLACE(KK_TBL_MEISHI_WK.KOKYAKU_NM,' ','') COLLATE Japanese_CI_AS_KS
					AND AITE.DEL_FLG = 0
					INNER JOIN KK_TBL_KIHONINFO AS KI
					--基本情報．会社コード=引数．会社コード 
					ON KI.KAISHA_CD = AITE.KAISHA_CD
					--基本情報．顧客管理NO=一時テーブル．顧客管理NO
					AND KI.KOKYAKUKANRI_NO = AITE.KOKYAKUKANRI_NO     
					--基本情報．削除フラグ
					AND KI.DEL_FLG = 0
					WHERE KK_TBL_MEISHI_WK.SESSION_ID = @SESSION_ID
						AND KK_TBL_MEISHI_WK.KAISHA_CD = @KAISHA_CD
						AND KK_TBL_MEISHI_WK.KOKYAKU_NM IS NOT NULL
						AND KK_TBL_MEISHI_WK.AYITETANTOSHA_NM IS NOT NULL
						AND KK_TBL_MEISHI_WK.LINE_NO = @LINE_NO
						AND KI.OYA_KOKYAKUKANRI_NO IS NOT NULL

					IF @COUNT11 = 1 BEGIN
						SELECT 						
						@KOKYAKUKANRI_NO121 = AITE.KOKYAKUKANRI_NO			
						FROM KK_TBL_MEISHI_WK
						LEFT JOIN KK_TBL_AITESAKI_TANTOSHA AITE
						ON AITE.KAISHA_CD = KK_TBL_MEISHI_WK.KAISHA_CD
						AND REPLACE(AITE.MAIL,' ','') = REPLACE(KK_TBL_MEISHI_WK.EMAIL,' ','')  COLLATE Japanese_CI_AS_KS
						AND AITE.DEL_FLG = 0
						INNER JOIN KK_TBL_KIHONINFO AS KI
						--基本情報．会社コード=引数．会社コード 
						ON KI.KAISHA_CD = AITE.KAISHA_CD
						--基本情報．顧客管理NO=一時テーブル．顧客管理NO
						AND KI.KOKYAKUKANRI_NO = AITE.KOKYAKUKANRI_NO     
						--基本情報．削除フラグ
						AND KI.DEL_FLG = 0
						WHERE KK_TBL_MEISHI_WK.SESSION_ID = @SESSION_ID
							AND KK_TBL_MEISHI_WK.KAISHA_CD = @KAISHA_CD
							AND KK_TBL_MEISHI_WK.EMAIL IS NOT NULL 
							AND KK_TBL_MEISHI_WK.LINE_NO = @LINE_NO
							AND KI.OYA_KOKYAKUKANRI_NO IS NOT NULL				
					END
					 
					IF @COUNT21 = 1 BEGIN			---比較順２and比較順1
							SELECT 
							@KOKYAKUKANRI_NO122 =  AITE.KOKYAKUKANRI_NO
							FROM KK_TBL_MEISHI_WK
							LEFT JOIN KK_TBL_AITESAKI_TANTOSHA AITE
							ON AITE.KAISHA_CD = KK_TBL_MEISHI_WK.KAISHA_CD
							AND REPLACE(AITE.AITESAKI_TANTOSHA_NM,' ','') = REPLACE(KK_TBL_MEISHI_WK.AYITETANTOSHA_NM,' ','')  COLLATE Japanese_CI_AS_KS
							AND REPLACE(AITE.KOKYAKU_NM,' ','') = REPLACE(KK_TBL_MEISHI_WK.KOKYAKU_NM,' ','')  COLLATE Japanese_CI_AS_KS
							AND AITE.DEL_FLG = 0
							INNER JOIN KK_TBL_KIHONINFO AS KI
							--基本情報．会社コード=引数．会社コード 
							ON KI.KAISHA_CD = AITE.KAISHA_CD
							--基本情報．顧客管理NO=一時テーブル．顧客管理NO
							AND KI.KOKYAKUKANRI_NO = AITE.KOKYAKUKANRI_NO     
							--基本情報．削除フラグ
							AND KI.DEL_FLG = 0
							WHERE KK_TBL_MEISHI_WK.SESSION_ID = @SESSION_ID
								AND KK_TBL_MEISHI_WK.KAISHA_CD = @KAISHA_CD
								AND KK_TBL_MEISHI_WK.KOKYAKU_NM IS NOT NULL
								AND KK_TBL_MEISHI_WK.AYITETANTOSHA_NM IS NOT NULL
								AND KK_TBL_MEISHI_WK.LINE_NO = @LINE_NO
								AND KI.OYA_KOKYAKUKANRI_NO IS NOT NULL
					END
					IF @COUNT11 = 1 AND @COUNT21 = 1 AND @KOKYAKUKANRI_NO121 = @KOKYAKUKANRI_NO122 BEGIN
						UPDATE KK_TBL_MEISHI_WK SET 
						KK_TBL_MEISHI_WK.KOKYAKUKANRI_NO = @KOKYAKUKANRI_NO121
						,KK_TBL_MEISHI_WK.ERROR_MSG = @ERR_MSG_AYITETANTOSHA_NM_FUKUSUU
						FROM KK_TBL_MEISHI_WK							
						WHERE KK_TBL_MEISHI_WK.SESSION_ID = @SESSION_ID
						AND KK_TBL_MEISHI_WK.KAISHA_CD = @KAISHA_CD
						AND KK_TBL_MEISHI_WK.LINE_NO = @LINE_NO
					END
					ELSE IF @COUNT11 = 1 BEGIN
						UPDATE KK_TBL_MEISHI_WK SET 
						KK_TBL_MEISHI_WK.KOKYAKUKANRI_NO = @KOKYAKUKANRI_NO121
						,KK_TBL_MEISHI_WK.ERROR_MSG = @ERR_MSG_AYITETANTOSHA_NM_FUKUSUU
						FROM KK_TBL_MEISHI_WK							
						WHERE KK_TBL_MEISHI_WK.SESSION_ID = @SESSION_ID
						AND KK_TBL_MEISHI_WK.KAISHA_CD = @KAISHA_CD
						AND KK_TBL_MEISHI_WK.LINE_NO = @LINE_NO
					END
					ELSE IF @COUNT21 = 1 BEGIN
						UPDATE KK_TBL_MEISHI_WK SET 
						KK_TBL_MEISHI_WK.KOKYAKUKANRI_NO = @KOKYAKUKANRI_NO122
						,KK_TBL_MEISHI_WK.ERROR_MSG = @ERR_MSG_AYITETANTOSHA_NM_FUKUSUU
						FROM KK_TBL_MEISHI_WK							
						WHERE KK_TBL_MEISHI_WK.SESSION_ID = @SESSION_ID
						AND KK_TBL_MEISHI_WK.KAISHA_CD = @KAISHA_CD
						AND KK_TBL_MEISHI_WK.LINE_NO = @LINE_NO

					END
					ELSE BEGIN
						SELECT 
						@COUNT3 = COUNT(AITE.TEL)
						FROM KK_TBL_MEISHI_WK
						LEFT JOIN KK_TBL_AITESAKI_TANTOSHA AITE
						ON AITE.KAISHA_CD = KK_TBL_MEISHI_WK.KAISHA_CD
						AND  REPLACE(REPLACE(AITE.TEL,'-',''),' ','') = REPLACE(REPLACE(KK_TBL_MEISHI_WK.TEL,'-',''),' ','')
						AND AITE.DEL_FLG = 0
						INNER JOIN KK_TBL_KIHONINFO AS KI
						--基本情報．会社コード=引数．会社コード 
						ON KI.KAISHA_CD = AITE.KAISHA_CD
						--基本情報．顧客管理NO=一時テーブル．顧客管理NO
						AND KI.KOKYAKUKANRI_NO = AITE.KOKYAKUKANRI_NO     
						--基本情報．削除フラグ
						AND KI.DEL_FLG = 0
						WHERE KK_TBL_MEISHI_WK.SESSION_ID = @SESSION_ID
							AND KK_TBL_MEISHI_WK.KAISHA_CD = @KAISHA_CD
							AND KK_TBL_MEISHI_WK.TEL IS NOT NULL 
							AND KK_TBL_MEISHI_WK.LINE_NO = @LINE_NO
							AND KI.OYA_KOKYAKUKANRI_NO IS NOT NULL

						IF @COUNT3 =1 BEGIN	   --比較順3  TEL	
							UPDATE KK_TBL_MEISHI_WK SET 
							KK_TBL_MEISHI_WK.KOKYAKUKANRI_NO = AITE.KOKYAKUKANRI_NO
							FROM KK_TBL_MEISHI_WK
							LEFT JOIN KK_TBL_AITESAKI_TANTOSHA AITE
							ON AITE.KAISHA_CD = KK_TBL_MEISHI_WK.KAISHA_CD
							AND  REPLACE(REPLACE(AITE.TEL,'-',''),' ','') = REPLACE(REPLACE(KK_TBL_MEISHI_WK.TEL,'-',''),' ','')
							WHERE KK_TBL_MEISHI_WK.SESSION_ID = @SESSION_ID
							AND KK_TBL_MEISHI_WK.KAISHA_CD = @KAISHA_CD
							AND KK_TBL_MEISHI_WK.LINE_NO = @LINE_NO
							AND KK_TBL_MEISHI_WK.TEL IS NOT NULL 
							AND AITE.KOKYAKUKANRI_NO IS NOT NULL
						END
							ELSE BEGIN
								SELECT 
								@COUNT4 = COUNT(AITE.FAX)
								FROM KK_TBL_MEISHI_WK
								LEFT JOIN KK_TBL_AITESAKI_TANTOSHA AITE
								ON AITE.KAISHA_CD = KK_TBL_MEISHI_WK.KAISHA_CD
								AND  REPLACE(REPLACE(AITE.FAX,'-',''),' ','') = REPLACE(REPLACE(KK_TBL_MEISHI_WK.FAX,'-',''),' ','')
								AND AITE.DEL_FLG = 0
								INNER JOIN KK_TBL_KIHONINFO AS KI
								--基本情報．会社コード=引数．会社コード 
								ON KI.KAISHA_CD = AITE.KAISHA_CD
								--基本情報．顧客管理NO=一時テーブル．顧客管理NO
								AND KI.KOKYAKUKANRI_NO = AITE.KOKYAKUKANRI_NO     
								--基本情報．削除フラグ
								AND KI.DEL_FLG = 0
								WHERE KK_TBL_MEISHI_WK.SESSION_ID = @SESSION_ID
									AND KK_TBL_MEISHI_WK.KAISHA_CD = @KAISHA_CD
									AND KK_TBL_MEISHI_WK.FAX IS NOT NULL 
									AND KK_TBL_MEISHI_WK.LINE_NO = @LINE_NO
									AND KI.OYA_KOKYAKUKANRI_NO IS NOT NULL

								IF @COUNT4 =1 BEGIN	   --比較順4  FAX	
									UPDATE KK_TBL_MEISHI_WK SET 
									KK_TBL_MEISHI_WK.KOKYAKUKANRI_NO = AITE.KOKYAKUKANRI_NO
									FROM KK_TBL_MEISHI_WK
									LEFT JOIN KK_TBL_AITESAKI_TANTOSHA AITE
									ON AITE.KAISHA_CD = KK_TBL_MEISHI_WK.KAISHA_CD
									AND  REPLACE(REPLACE(AITE.FAX,'-',''),' ','') = REPLACE(REPLACE(KK_TBL_MEISHI_WK.FAX,'-',''),' ','')
									AND AITE.DEL_FLG = 0
									WHERE KK_TBL_MEISHI_WK.SESSION_ID = @SESSION_ID
									AND KK_TBL_MEISHI_WK.KAISHA_CD = @KAISHA_CD
									AND KK_TBL_MEISHI_WK.LINE_NO = @LINE_NO
									AND KK_TBL_MEISHI_WK.FAX IS NOT NULL 
									AND AITE.KOKYAKUKANRI_NO IS NOT NULL
								END
								ELSE BEGIN
									SELECT 
									@COUNT51 = COUNT(KIHON1.KOKYAKUKANRI_NO)             ---比較順5
									FROM KK_TBL_MEISHI_WK
									LEFT JOIN KK_TBL_KIHONINFO KIHON1
									ON	KIHON1.KAISHA_CD = KK_TBL_MEISHI_WK.KAISHA_CD
									 	AND REPLACE(REPLACE(KIHON1.TEL,' ',''),'-','') =REPLACE(REPLACE(KK_TBL_MEISHI_WK.TEL,' ',''),'-','')
										AND KIHON1.DEL_FLG = 0
									WHERE KK_TBL_MEISHI_WK.SESSION_ID = @SESSION_ID
										AND KK_TBL_MEISHI_WK.KAISHA_CD = @KAISHA_CD
										AND KK_TBL_MEISHI_WK.LINE_NO = @LINE_NO
										AND KK_TBL_MEISHI_WK.TEL IS NOT NULL
										AND KIHON1.OYA_KOKYAKUKANRI_NO IS NOT NULL
										
									SELECT 
									@COUNT52 = COUNT(KIHON2.KOKYAKUKANRI_NO)             ---比較順5
									FROM KK_TBL_MEISHI_WK
									LEFT JOIN BC_MST_TORIHIKISAKI TORI
									 ON	TORI.KAISHA_CD = KK_TBL_MEISHI_WK.KAISHA_CD
									 	AND REPLACE(REPLACE(TORI.TEL,' ',''),'-','') =REPLACE(REPLACE(KK_TBL_MEISHI_WK.TEL,' ',''),'-','')											
										AND TORI.DEL_FLG = 0
										AND TORI.MUKOU_FLG = 0
									INNER JOIN KK_TBL_KIHONINFO KIHON2
									ON	KIHON2.KAISHA_CD = KK_TBL_MEISHI_WK.KAISHA_CD
										AND TORI.TORIHIKISAKI_CD = KIHON2.TORIHIKISAKI_CD										 
										AND KIHON2.DEL_FLG = 0
									WHERE KK_TBL_MEISHI_WK.SESSION_ID = @SESSION_ID
										AND KK_TBL_MEISHI_WK.KAISHA_CD = @KAISHA_CD
										AND KK_TBL_MEISHI_WK.LINE_NO = @LINE_NO
										AND KK_TBL_MEISHI_WK.TEL IS NOT NULL
										AND KIHON2.OYA_KOKYAKUKANRI_NO IS NOT NULL
									SELECT 
									@COUNT53 = COUNT(KIHON3.KOKYAKUKANRI_NO)             ---比較順5
									FROM KK_TBL_MEISHI_WK
										LEFT JOIN BC_MST_TOKUISAKI TOKUYI
									 ON	TOKUYI.KAISHA_CD = KK_TBL_MEISHI_WK.KAISHA_CD
									 	AND REPLACE(REPLACE(TOKUYI.TOKUISAKI_TANTO_TEL,' ',''),'-','') =REPLACE(REPLACE(KK_TBL_MEISHI_WK.TEL,' ',''),'-','')											
										AND TOKUYI.DEL_FLG = 0
										AND TOKUYI.MUKOU_FLG = 0
									INNER JOIN KK_TBL_KIHONINFO KIHON3
									ON	KIHON3.KAISHA_CD = KK_TBL_MEISHI_WK.KAISHA_CD
										AND TOKUYI.TOKUISAKI_CD = KIHON3.TORIHIKISAKI_CD										 
										AND KIHON3.DEL_FLG = 0
									WHERE KK_TBL_MEISHI_WK.SESSION_ID = @SESSION_ID
										AND KK_TBL_MEISHI_WK.KAISHA_CD = @KAISHA_CD
										AND KK_TBL_MEISHI_WK.LINE_NO = @LINE_NO
										AND KK_TBL_MEISHI_WK.TEL IS NOT NULL
										AND KIHON3.OYA_KOKYAKUKANRI_NO IS NOT NULL

									SELECT 
									@COUNT54 = COUNT(KIHON4.KOKYAKUKANRI_NO)             ---比較順5
									FROM KK_TBL_MEISHI_WK
									LEFT JOIN BC_MST_SHUKKASAKI SHUKA
									 ON	SHUKA.KAISHA_CD = KK_TBL_MEISHI_WK.KAISHA_CD
									 	AND REPLACE(REPLACE(SHUKA.TEL,' ',''),'-','') =REPLACE(REPLACE(KK_TBL_MEISHI_WK.TEL,' ',''),'-','')											
										AND SHUKA.DEL_FLG = 0
										AND SHUKA.MUKOU_FLG = 0
									INNER JOIN KK_TBL_KIHONINFO KIHON4
									ON	KIHON4.KAISHA_CD = KK_TBL_MEISHI_WK.KAISHA_CD
										AND SHUKA.SHUKKASAKI_CD = KIHON4.TORIHIKISAKI_CD										 
										AND KIHON4.DEL_FLG = 0
									WHERE KK_TBL_MEISHI_WK.SESSION_ID = @SESSION_ID
										AND KK_TBL_MEISHI_WK.KAISHA_CD = @KAISHA_CD
										AND KK_TBL_MEISHI_WK.LINE_NO = @LINE_NO
										AND KK_TBL_MEISHI_WK.TEL IS NOT NULL
										AND KIHON4.OYA_KOKYAKUKANRI_NO IS NOT NULL

									SELECT 
									@COUNT55 = COUNT(KIHON5.KOKYAKUKANRI_NO)             ---比較順5
									FROM KK_TBL_MEISHI_WK
									LEFT JOIN BC_MST_SHIRESAKI SHIRE
									 ON	SHIRE.KAISHA_CD = KK_TBL_MEISHI_WK.KAISHA_CD
									 	AND REPLACE(REPLACE(SHIRE.SHIRESAKI_TANTO_TEL,' ',''),'-','') =REPLACE(REPLACE(KK_TBL_MEISHI_WK.TEL,' ',''),'-','')											
										AND SHIRE.DEL_FLG = 0
										AND SHIRE.MUKOU_FLG = 0
									INNER JOIN KK_TBL_KIHONINFO KIHON5
									ON	KIHON5.KAISHA_CD = KK_TBL_MEISHI_WK.KAISHA_CD
										AND SHIRE.SHIRESAKI_CD = KIHON5.TORIHIKISAKI_CD										 
										AND KIHON5.DEL_FLG = 0
									WHERE KK_TBL_MEISHI_WK.SESSION_ID = @SESSION_ID
										AND KK_TBL_MEISHI_WK.KAISHA_CD = @KAISHA_CD
										AND KK_TBL_MEISHI_WK.LINE_NO = @LINE_NO
										AND KK_TBL_MEISHI_WK.TEL IS NOT NULL							
										AND KIHON5.OYA_KOKYAKUKANRI_NO IS NOT NULL
																				 
									UPDATE KK_TBL_MEISHI_WK SET             ---比較順5
									KK_TBL_MEISHI_WK.KOKYAKUKANRI_NO = 
									CASE WHEN KIHON.TEL IS NOT NULL AND KIHON.KOKYAKUKANRI_NO IS NOT NULL THEN --#7～11いずれかの一致で判定
											KIHON.KOKYAKUKANRI_NO
										 ELSE KK_TBL_MEISHI_WK.KOKYAKUKANRI_NO  END
									FROM KK_TBL_MEISHI_WK
									LEFT JOIN KK_TBL_KIHONINFO KIHON
									ON	KIHON.KAISHA_CD = KK_TBL_MEISHI_WK.KAISHA_CD
									 	AND REPLACE(REPLACE(KIHON.TEL,' ',''),'-','') =REPLACE(REPLACE(KK_TBL_MEISHI_WK.TEL,' ',''),'-','')
										AND KIHON.DEL_FLG = 0
									WHERE KK_TBL_MEISHI_WK.SESSION_ID = @SESSION_ID
										AND KK_TBL_MEISHI_WK.KAISHA_CD = @KAISHA_CD
										AND KK_TBL_MEISHI_WK.LINE_NO = @LINE_NO
										AND @COUNT51 = 1

									IF @@ROWCOUNT = 0 BEGIN
									UPDATE KK_TBL_MEISHI_WK SET            
									KK_TBL_MEISHI_WK.KOKYAKUKANRI_NO = 
									CASE WHEN KIHON.KAISHA_CD IS NOT NULL AND KIHON.KOKYAKUKANRI_NO IS NOT NULL THEN
											KIHON.KOKYAKUKANRI_NO 
											ELSE KK_TBL_MEISHI_WK.KOKYAKUKANRI_NO  END
									FROM KK_TBL_MEISHI_WK
									 LEFT JOIN BC_MST_TORIHIKISAKI TORI
									 ON	TORI.KAISHA_CD = KK_TBL_MEISHI_WK.KAISHA_CD
									 	AND REPLACE(REPLACE(TORI.TEL,' ',''),'-','') =REPLACE(REPLACE(KK_TBL_MEISHI_WK.TEL,' ',''),'-','')											
										AND TORI.DEL_FLG = 0
										AND TORI.MUKOU_FLG = 0
									INNER JOIN KK_TBL_KIHONINFO KIHON
									ON	KIHON.KAISHA_CD = KK_TBL_MEISHI_WK.KAISHA_CD
										AND TORI.TORIHIKISAKI_CD = KIHON.TORIHIKISAKI_CD										 
										AND KIHON.DEL_FLG = 0
									WHERE KK_TBL_MEISHI_WK.SESSION_ID = @SESSION_ID
										AND KK_TBL_MEISHI_WK.KAISHA_CD = @KAISHA_CD
										AND KK_TBL_MEISHI_WK.LINE_NO = @LINE_NO
										AND @COUNT52 = 1
										
									END	

									IF @@ROWCOUNT = 0 BEGIN
									UPDATE KK_TBL_MEISHI_WK SET            
									KK_TBL_MEISHI_WK.KOKYAKUKANRI_NO = 
									CASE WHEN KIHON.KAISHA_CD IS NOT NULL AND KIHON.KOKYAKUKANRI_NO IS NOT NULL THEN
											KIHON.KOKYAKUKANRI_NO 
											ELSE KK_TBL_MEISHI_WK.KOKYAKUKANRI_NO  END
									FROM KK_TBL_MEISHI_WK
									 LEFT JOIN BC_MST_TOKUISAKI TOKUYI
									 ON	TOKUYI.KAISHA_CD = KK_TBL_MEISHI_WK.KAISHA_CD
									 	AND REPLACE(REPLACE(TOKUYI.TOKUISAKI_TANTO_TEL,' ',''),'-','') =REPLACE(REPLACE(KK_TBL_MEISHI_WK.TEL,' ',''),'-','')											
										AND TOKUYI.DEL_FLG = 0
										AND TOKUYI.MUKOU_FLG = 0
									INNER JOIN KK_TBL_KIHONINFO KIHON
									ON	KIHON.KAISHA_CD = KK_TBL_MEISHI_WK.KAISHA_CD
										AND TOKUYI.TOKUISAKI_CD = KIHON.TORIHIKISAKI_CD										 
										AND KIHON.DEL_FLG = 0
									WHERE KK_TBL_MEISHI_WK.SESSION_ID = @SESSION_ID
										AND KK_TBL_MEISHI_WK.KAISHA_CD = @KAISHA_CD
										AND KK_TBL_MEISHI_WK.LINE_NO = @LINE_NO
										AND @COUNT53 = 1
									END

									IF @@ROWCOUNT = 0 BEGIN
									UPDATE KK_TBL_MEISHI_WK SET            
									KK_TBL_MEISHI_WK.KOKYAKUKANRI_NO = 
									CASE WHEN KIHON.KAISHA_CD IS NOT NULL AND KIHON.KOKYAKUKANRI_NO IS NOT NULL THEN
											KIHON.KOKYAKUKANRI_NO 
										ELSE KK_TBL_MEISHI_WK.KOKYAKUKANRI_NO  END	
									FROM KK_TBL_MEISHI_WK
									 LEFT JOIN BC_MST_SHUKKASAKI SHUKA
									 ON	SHUKA.KAISHA_CD = KK_TBL_MEISHI_WK.KAISHA_CD
									 	AND REPLACE(REPLACE(SHUKA.TEL,' ',''),'-','') =REPLACE(REPLACE(KK_TBL_MEISHI_WK.TEL,' ',''),'-','')											
										AND SHUKA.DEL_FLG = 0
										AND SHUKA.MUKOU_FLG = 0
									INNER JOIN KK_TBL_KIHONINFO KIHON
									ON	KIHON.KAISHA_CD = KK_TBL_MEISHI_WK.KAISHA_CD
										AND SHUKA.SHUKKASAKI_CD = KIHON.TORIHIKISAKI_CD										 
										AND KIHON.DEL_FLG = 0
									WHERE KK_TBL_MEISHI_WK.SESSION_ID = @SESSION_ID
										AND KK_TBL_MEISHI_WK.KAISHA_CD = @KAISHA_CD
										AND KK_TBL_MEISHI_WK.LINE_NO = @LINE_NO
										AND @COUNT54 = 1
									END

									IF @@ROWCOUNT = 0 BEGIN
									UPDATE KK_TBL_MEISHI_WK SET            
									KK_TBL_MEISHI_WK.KOKYAKUKANRI_NO = 
									CASE WHEN KIHON.KAISHA_CD IS NOT NULL AND KIHON.KOKYAKUKANRI_NO IS NOT NULL THEN
											KIHON.KOKYAKUKANRI_NO 
										ELSE KK_TBL_MEISHI_WK.KOKYAKUKANRI_NO  END
									FROM KK_TBL_MEISHI_WK
									 LEFT JOIN BC_MST_SHIRESAKI SHIRE
									 ON	SHIRE.KAISHA_CD = KK_TBL_MEISHI_WK.KAISHA_CD
									 	AND REPLACE(REPLACE(SHIRE.SHIRESAKI_TANTO_TEL,' ',''),'-','') =REPLACE(REPLACE(KK_TBL_MEISHI_WK.TEL,' ',''),'-','')											
										AND SHIRE.DEL_FLG = 0
										AND SHIRE.MUKOU_FLG = 0
									INNER JOIN KK_TBL_KIHONINFO KIHON
									ON	KIHON.KAISHA_CD = KK_TBL_MEISHI_WK.KAISHA_CD
										AND SHIRE.SHIRESAKI_CD = KIHON.TORIHIKISAKI_CD										 
										AND KIHON.DEL_FLG = 0
									WHERE KK_TBL_MEISHI_WK.SESSION_ID = @SESSION_ID
										AND KK_TBL_MEISHI_WK.KAISHA_CD = @KAISHA_CD
										AND KK_TBL_MEISHI_WK.LINE_NO = @LINE_NO
										AND @COUNT55 = 1
									END																						

									IF @@ROWCOUNT = 0 BEGIN       --比較順６								
										SELECT 
										@COUNT61 = COUNT(KIHON1.KOKYAKUKANRI_NO)             ---比較順6
										FROM KK_TBL_MEISHI_WK
										LEFT JOIN KK_TBL_KIHONINFO KIHON1
										ON	KIHON1.KAISHA_CD = KK_TBL_MEISHI_WK.KAISHA_CD
										 	AND REPLACE(REPLACE(KIHON1.ZIP_CD,' ',''),'-','') =REPLACE(REPLACE(KK_TBL_MEISHI_WK.ZIP_CD,' ',''),'-','')
											AND REPLACE(KIHON1.KOKYAKU_NM,' ','') LIKE '%' + REPLACE(KK_TBL_MEISHI_WK.KOKYAKU_NM,' ','') + '%'
											AND KIHON1.DEL_FLG = 0
										WHERE KK_TBL_MEISHI_WK.SESSION_ID = @SESSION_ID
											AND KK_TBL_MEISHI_WK.KAISHA_CD = @KAISHA_CD
											AND KK_TBL_MEISHI_WK.LINE_NO = @LINE_NO
											AND KK_TBL_MEISHI_WK.ZIP_CD IS NOT NULL
											AND KK_TBL_MEISHI_WK.KOKYAKU_NM IS NOT NULL
											AND KIHON1.OYA_KOKYAKUKANRI_NO IS NOT NULL

										SELECT 
										@COUNT62 = COUNT(KIHON2.KOKYAKUKANRI_NO)
										FROM KK_TBL_MEISHI_WK
										LEFT JOIN BC_MST_TORIHIKISAKI TORI
										 ON	TORI.KAISHA_CD = KK_TBL_MEISHI_WK.KAISHA_CD
										 	AND REPLACE(REPLACE(TORI.ZIP_CD,' ',''),'-','') =REPLACE(REPLACE(KK_TBL_MEISHI_WK.ZIP_CD,' ',''),'-','')
											AND REPLACE(TORI.TORIHIKISAKI_NM,' ','') LIKE '%' + REPLACE(KK_TBL_MEISHI_WK.KOKYAKU_NM,' ','') + '%' COLLATE Japanese_CI_AS_KS
											AND TORI.DEL_FLG = 0
											AND TORI.MUKOU_FLG = 0
										INNER JOIN KK_TBL_KIHONINFO KIHON2
										ON	KIHON2.KAISHA_CD = KK_TBL_MEISHI_WK.KAISHA_CD
											AND TORI.TORIHIKISAKI_CD = KIHON2.TORIHIKISAKI_CD										 
											AND KIHON2.DEL_FLG = 0
										WHERE KK_TBL_MEISHI_WK.SESSION_ID = @SESSION_ID
											AND KK_TBL_MEISHI_WK.KAISHA_CD = @KAISHA_CD
											AND KK_TBL_MEISHI_WK.LINE_NO = @LINE_NO
											AND KK_TBL_MEISHI_WK.ZIP_CD IS NOT NULL
											AND KK_TBL_MEISHI_WK.KOKYAKU_NM IS NOT NULL
											AND KIHON2.OYA_KOKYAKUKANRI_NO IS NOT NULL

										SELECT 
										@COUNT63 = COUNT(KIHON3.KOKYAKUKANRI_NO)
										FROM KK_TBL_MEISHI_WK
										LEFT JOIN BC_MST_SHUKKASAKI SHUKA
										 ON  SHUKA.KAISHA_CD = KK_TBL_MEISHI_WK.KAISHA_CD
											 AND REPLACE(REPLACE(SHUKA.ZIP_CD,' ',''),'-','') = REPLACE(REPLACE(KK_TBL_MEISHI_WK.ZIP_CD,' ',''),'-','')
											 AND REPLACE(SHUKA.SHUKKASAKI_NM,' ','') LIKE '%' + REPLACE(KK_TBL_MEISHI_WK.KOKYAKU_NM,' ','') + '%' COLLATE Japanese_CI_AS_KS
											 AND SHUKA.DEL_FLG = 0
											 AND SHUKA.MUKOU_FLG = 0
										INNER JOIN KK_TBL_KIHONINFO KIHON3
										ON	KIHON3.KAISHA_CD = KK_TBL_MEISHI_WK.KAISHA_CD
											AND SHUKA.SHUKKASAKI_CD = KIHON3.TORIHIKISAKI_CD										 
											AND KIHON3.DEL_FLG = 0
										WHERE KK_TBL_MEISHI_WK.SESSION_ID = @SESSION_ID
											AND KK_TBL_MEISHI_WK.KAISHA_CD = @KAISHA_CD
											AND KK_TBL_MEISHI_WK.LINE_NO = @LINE_NO
											AND KK_TBL_MEISHI_WK.ZIP_CD IS NOT NULL
											AND KK_TBL_MEISHI_WK.KOKYAKU_NM IS NOT NULL										
											AND KIHON3.OYA_KOKYAKUKANRI_NO IS NOT NULL
											 
										UPDATE KK_TBL_MEISHI_WK SET             ---比較順6
										KK_TBL_MEISHI_WK.KOKYAKUKANRI_NO = 
										CASE WHEN KIHON.ZIP_CD IS NOT NULL AND KIHON.KOKYAKU_NM IS NOT NULL AND KIHON.KOKYAKUKANRI_NO IS NOT NULL THEN --#1～3#4～6いずれかの一致で判定
												KIHON.KOKYAKUKANRI_NO
											 ELSE KK_TBL_MEISHI_WK.KOKYAKUKANRI_NO  END
										FROM KK_TBL_MEISHI_WK
										LEFT JOIN KK_TBL_KIHONINFO KIHON
										ON	KIHON.KAISHA_CD = KK_TBL_MEISHI_WK.KAISHA_CD
										 	AND REPLACE(REPLACE(KIHON.ZIP_CD,' ',''),'-','') =REPLACE(REPLACE(KK_TBL_MEISHI_WK.ZIP_CD,' ',''),'-','')
											AND REPLACE(KIHON.KOKYAKU_NM,' ','') LIKE '%' + REPLACE(KK_TBL_MEISHI_WK.KOKYAKU_NM,' ','') + '%' COLLATE Japanese_CI_AS_KS
											AND KIHON.DEL_FLG = 0
										WHERE KK_TBL_MEISHI_WK.SESSION_ID = @SESSION_ID
											AND KK_TBL_MEISHI_WK.KAISHA_CD = @KAISHA_CD
											AND KK_TBL_MEISHI_WK.LINE_NO = @LINE_NO
											AND @COUNT61 = 1
											
										IF @@ROWCOUNT = 0 BEGIN
										UPDATE KK_TBL_MEISHI_WK SET             ---比較順6
										KK_TBL_MEISHI_WK.KOKYAKUKANRI_NO = 
										CASE WHEN KIHON.KAISHA_CD IS NOT NULL AND KIHON.KOKYAKUKANRI_NO IS NOT NULL THEN --#1～3#4～6いずれかの一致で判定
												KIHON.KOKYAKUKANRI_NO
											 ELSE KK_TBL_MEISHI_WK.KOKYAKUKANRI_NO  END
										FROM KK_TBL_MEISHI_WK
										LEFT JOIN BC_MST_TORIHIKISAKI TORI
										 ON	TORI.KAISHA_CD = KK_TBL_MEISHI_WK.KAISHA_CD
										 	AND REPLACE(REPLACE(TORI.ZIP_CD,' ',''),'-','') =REPLACE(REPLACE(KK_TBL_MEISHI_WK.ZIP_CD,' ',''),'-','')
											AND REPLACE(TORI.TORIHIKISAKI_NM,' ','') LIKE '%' + REPLACE(KK_TBL_MEISHI_WK.KOKYAKU_NM,' ','') + '%' COLLATE Japanese_CI_AS_KS
											AND TORI.DEL_FLG = 0
											AND TORI.MUKOU_FLG = 0
										INNER JOIN KK_TBL_KIHONINFO KIHON
										ON	KIHON.KAISHA_CD = KK_TBL_MEISHI_WK.KAISHA_CD
											AND TORI.TORIHIKISAKI_CD = KIHON.TORIHIKISAKI_CD										 
											AND KIHON.DEL_FLG = 0
										WHERE KK_TBL_MEISHI_WK.SESSION_ID = @SESSION_ID
											AND KK_TBL_MEISHI_WK.KAISHA_CD = @KAISHA_CD
											AND KK_TBL_MEISHI_WK.LINE_NO = @LINE_NO
											AND @COUNT62 = 1
										END
										
										IF @@ROWCOUNT = 0 BEGIN
										UPDATE KK_TBL_MEISHI_WK SET             ---比較順6
										KK_TBL_MEISHI_WK.KOKYAKUKANRI_NO = 
										CASE WHEN KIHON.KAISHA_CD IS NOT NULL AND KIHON.KOKYAKUKANRI_NO IS NOT NULL THEN --#1～3#4～6いずれかの一致で判定
												KIHON.KOKYAKUKANRI_NO
											 ELSE KK_TBL_MEISHI_WK.KOKYAKUKANRI_NO  END
										FROM KK_TBL_MEISHI_WK
										LEFT JOIN BC_MST_SHUKKASAKI SHUKA
										 ON  SHUKA.KAISHA_CD = KK_TBL_MEISHI_WK.KAISHA_CD
											 AND REPLACE(REPLACE(SHUKA.ZIP_CD,' ',''),'-','') = REPLACE(REPLACE(KK_TBL_MEISHI_WK.ZIP_CD,' ',''),'-','')
											 AND REPLACE(SHUKA.SHUKKASAKI_NM,' ','') LIKE '%' + REPLACE(KK_TBL_MEISHI_WK.KOKYAKU_NM,' ','') + '%' COLLATE Japanese_CI_AS_KS
											 AND SHUKA.DEL_FLG = 0
											 AND SHUKA.MUKOU_FLG = 0
										INNER JOIN KK_TBL_KIHONINFO KIHON
										ON	KIHON.KAISHA_CD = KK_TBL_MEISHI_WK.KAISHA_CD
											AND SHUKA.SHUKKASAKI_CD = KIHON.TORIHIKISAKI_CD										 
											AND KIHON.DEL_FLG = 0
										WHERE KK_TBL_MEISHI_WK.SESSION_ID = @SESSION_ID
											AND KK_TBL_MEISHI_WK.KAISHA_CD = @KAISHA_CD
											AND KK_TBL_MEISHI_WK.LINE_NO = @LINE_NO
											AND @COUNT63 = 1
										END

										SELECT 
										@COUNT64 = COUNT(KIHON1.KOKYAKUKANRI_NO)             ---比較順6
										FROM KK_TBL_MEISHI_WK
										LEFT JOIN KK_TBL_KIHONINFO KIHON1
										ON	KIHON1.KAISHA_CD = KK_TBL_MEISHI_WK.KAISHA_CD
										 	AND REPLACE(REPLACE(KIHON1.ZIP_CD,' ',''),'-','') =REPLACE(REPLACE(KK_TBL_MEISHI_WK.ZIP_CD,' ',''),'-','')
											AND REPLACE(KIHON1.KOKYAKU_NM,' ','')= REPLACE(KK_TBL_MEISHI_WK.KOKYAKU_NM,' ','')
											AND KIHON1.DEL_FLG = 0
										WHERE KK_TBL_MEISHI_WK.SESSION_ID = @SESSION_ID
											AND KK_TBL_MEISHI_WK.KAISHA_CD = @KAISHA_CD
											AND KK_TBL_MEISHI_WK.LINE_NO = @LINE_NO
											AND KK_TBL_MEISHI_WK.ZIP_CD IS NOT NULL
											AND KK_TBL_MEISHI_WK.KOKYAKU_NM IS NOT NULL
											AND KIHON1.OYA_KOKYAKUKANRI_NO IS NOT NULL

										SELECT 
										@COUNT65 = COUNT(KIHON2.KOKYAKUKANRI_NO)
										FROM KK_TBL_MEISHI_WK
										LEFT JOIN BC_MST_TORIHIKISAKI TORI
										 ON	TORI.KAISHA_CD = KK_TBL_MEISHI_WK.KAISHA_CD
										 	AND REPLACE(REPLACE(TORI.ZIP_CD,' ',''),'-','') =REPLACE(REPLACE(KK_TBL_MEISHI_WK.ZIP_CD,' ',''),'-','')
											AND REPLACE(TORI.TORIHIKISAKI_NM,' ','') = REPLACE(KK_TBL_MEISHI_WK.KOKYAKU_NM,' ','')
											AND TORI.DEL_FLG = 0
											AND TORI.MUKOU_FLG = 0
										INNER JOIN KK_TBL_KIHONINFO KIHON2
										ON	KIHON2.KAISHA_CD = KK_TBL_MEISHI_WK.KAISHA_CD
											AND TORI.TORIHIKISAKI_CD = KIHON2.TORIHIKISAKI_CD										 
											AND KIHON2.DEL_FLG = 0
										WHERE KK_TBL_MEISHI_WK.SESSION_ID = @SESSION_ID
											AND KK_TBL_MEISHI_WK.KAISHA_CD = @KAISHA_CD
											AND KK_TBL_MEISHI_WK.LINE_NO = @LINE_NO
											AND KK_TBL_MEISHI_WK.ZIP_CD IS NOT NULL
											AND KK_TBL_MEISHI_WK.KOKYAKU_NM IS NOT NULL
											AND KIHON2.OYA_KOKYAKUKANRI_NO IS NOT NULL

										SELECT 
										@COUNT66 = COUNT(KIHON3.KOKYAKUKANRI_NO)
										FROM KK_TBL_MEISHI_WK
										LEFT JOIN BC_MST_SHUKKASAKI SHUKA
										 ON  SHUKA.KAISHA_CD = KK_TBL_MEISHI_WK.KAISHA_CD
											 AND REPLACE(REPLACE(SHUKA.ZIP_CD,' ',''),'-','') = REPLACE(REPLACE(KK_TBL_MEISHI_WK.ZIP_CD,' ',''),'-','')
											 AND REPLACE(SHUKA.SHUKKASAKI_NM,' ','') = REPLACE(KK_TBL_MEISHI_WK.KOKYAKU_NM,' ','') 
											 AND SHUKA.DEL_FLG = 0
											 AND SHUKA.MUKOU_FLG = 0
										INNER JOIN KK_TBL_KIHONINFO KIHON3
										ON	KIHON3.KAISHA_CD = KK_TBL_MEISHI_WK.KAISHA_CD
											AND SHUKA.SHUKKASAKI_CD = KIHON3.TORIHIKISAKI_CD										 
											AND KIHON3.DEL_FLG = 0
										WHERE KK_TBL_MEISHI_WK.SESSION_ID = @SESSION_ID
											AND KK_TBL_MEISHI_WK.KAISHA_CD = @KAISHA_CD
											AND KK_TBL_MEISHI_WK.LINE_NO = @LINE_NO
											AND KK_TBL_MEISHI_WK.ZIP_CD IS NOT NULL
											AND KK_TBL_MEISHI_WK.KOKYAKU_NM IS NOT NULL										
											AND KIHON3.OYA_KOKYAKUKANRI_NO IS NOT NULL
 
										UPDATE KK_TBL_MEISHI_WK SET             ---比較順6
										KK_TBL_MEISHI_WK.KOKYAKUKANRI_NO = 
										CASE WHEN KIHON.ZIP_CD IS NOT NULL AND KIHON.KOKYAKU_NM IS NOT NULL AND KIHON.KOKYAKUKANRI_NO IS NOT NULL THEN --#1～3#4～6いずれかの一致で判定
												KIHON.KOKYAKUKANRI_NO
											 ELSE KK_TBL_MEISHI_WK.KOKYAKUKANRI_NO  END
										FROM KK_TBL_MEISHI_WK
										LEFT JOIN KK_TBL_KIHONINFO KIHON
										ON	KIHON.KAISHA_CD = KK_TBL_MEISHI_WK.KAISHA_CD
										 	AND REPLACE(REPLACE(KIHON.ZIP_CD,' ',''),'-','') =REPLACE(REPLACE(KK_TBL_MEISHI_WK.ZIP_CD,' ',''),'-','')
											AND REPLACE(KIHON.KOKYAKU_NM,' ','') =  REPLACE(KK_TBL_MEISHI_WK.KOKYAKU_NM,' ','')
											AND KIHON.DEL_FLG = 0
										WHERE KK_TBL_MEISHI_WK.SESSION_ID = @SESSION_ID
											AND KK_TBL_MEISHI_WK.KAISHA_CD = @KAISHA_CD
											AND KK_TBL_MEISHI_WK.LINE_NO = @LINE_NO
											AND @COUNT64 = 1
											
										IF @@ROWCOUNT = 0 BEGIN
										UPDATE KK_TBL_MEISHI_WK SET             ---比較順6
										KK_TBL_MEISHI_WK.KOKYAKUKANRI_NO = 
										CASE WHEN KIHON.KAISHA_CD IS NOT NULL AND KIHON.KOKYAKUKANRI_NO IS NOT NULL THEN --#1～3#4～6いずれかの一致で判定
												KIHON.KOKYAKUKANRI_NO
											 ELSE KK_TBL_MEISHI_WK.KOKYAKUKANRI_NO  END
										FROM KK_TBL_MEISHI_WK
										LEFT JOIN BC_MST_TORIHIKISAKI TORI
										 ON	TORI.KAISHA_CD = KK_TBL_MEISHI_WK.KAISHA_CD
										 	AND REPLACE(REPLACE(TORI.ZIP_CD,' ',''),'-','') =REPLACE(REPLACE(KK_TBL_MEISHI_WK.ZIP_CD,' ',''),'-','')
											AND REPLACE(TORI.TORIHIKISAKI_NM,' ','') = REPLACE(KK_TBL_MEISHI_WK.KOKYAKU_NM,' ','') 
											AND TORI.DEL_FLG = 0
											AND TORI.MUKOU_FLG = 0
										INNER JOIN KK_TBL_KIHONINFO KIHON
										ON	KIHON.KAISHA_CD = KK_TBL_MEISHI_WK.KAISHA_CD
											AND TORI.TORIHIKISAKI_CD = KIHON.TORIHIKISAKI_CD										 
											AND KIHON.DEL_FLG = 0
										WHERE KK_TBL_MEISHI_WK.SESSION_ID = @SESSION_ID
											AND KK_TBL_MEISHI_WK.KAISHA_CD = @KAISHA_CD
											AND KK_TBL_MEISHI_WK.LINE_NO = @LINE_NO
											AND @COUNT65 = 1
										END
										
										IF @@ROWCOUNT = 0 BEGIN
										UPDATE KK_TBL_MEISHI_WK SET             ---比較順6
										KK_TBL_MEISHI_WK.KOKYAKUKANRI_NO = 
										CASE WHEN KIHON.KAISHA_CD IS NOT NULL AND KIHON.KOKYAKUKANRI_NO IS NOT NULL THEN --#1～3#4～6いずれかの一致で判定
												KIHON.KOKYAKUKANRI_NO
											 ELSE KK_TBL_MEISHI_WK.KOKYAKUKANRI_NO  END
										FROM KK_TBL_MEISHI_WK
										LEFT JOIN BC_MST_SHUKKASAKI SHUKA
										 ON  SHUKA.KAISHA_CD = KK_TBL_MEISHI_WK.KAISHA_CD
											 AND REPLACE(REPLACE(SHUKA.ZIP_CD,' ',''),'-','') = REPLACE(REPLACE(KK_TBL_MEISHI_WK.ZIP_CD,' ',''),'-','')
											 AND REPLACE(SHUKA.SHUKKASAKI_NM,' ','') = REPLACE(KK_TBL_MEISHI_WK.KOKYAKU_NM,' ','')
											 AND SHUKA.DEL_FLG = 0
											 AND SHUKA.MUKOU_FLG = 0
										INNER JOIN KK_TBL_KIHONINFO KIHON
										ON	KIHON.KAISHA_CD = KK_TBL_MEISHI_WK.KAISHA_CD
											AND SHUKA.SHUKKASAKI_CD = KIHON.TORIHIKISAKI_CD										 
											AND KIHON.DEL_FLG = 0
										WHERE KK_TBL_MEISHI_WK.SESSION_ID = @SESSION_ID
											AND KK_TBL_MEISHI_WK.KAISHA_CD = @KAISHA_CD
											AND KK_TBL_MEISHI_WK.LINE_NO = @LINE_NO
											AND @COUNT66 = 1
										END
										
									END
								END
							END	 
						END
					END
				END

		IF (@COUNT11 > 1 OR @COUNT21 > 1 OR @COUNT3 > 1 OR @COUNT4 > 1 OR @COUNT51 > 1 OR @COUNT52 > 1 OR @COUNT53 > 1 OR @COUNT54 > 1 OR @COUNT55 > 1
			OR @COUNT61 > 1 OR @COUNT62 > 1 OR @COUNT63 > 1 OR @COUNT64 > 1 OR @COUNT64 > 1 OR @COUNT66 > 1) BEGIN
			UPDATE KK_TBL_MEISHI_WK SET 
			KK_TBL_MEISHI_WK.AYITETANTOSHA_CD = NULL
			,KK_TBL_MEISHI_WK.ERROR_MSG = @ERR_MSG_KOKYAKU_NM_FUKUSUU
			FROM KK_TBL_MEISHI_WK
			WHERE KK_TBL_MEISHI_WK.SESSION_ID = @SESSION_ID
			AND KK_TBL_MEISHI_WK.KAISHA_CD = @KAISHA_CD
			AND KK_TBL_MEISHI_WK.LINE_NO = @LINE_NO
			AND KK_TBL_MEISHI_WK.KOKYAKUKANRI_NO IS NULL
			AND KK_TBL_MEISHI_WK.ERROR_MSG IS NULL
		END
		
		IF (@COUNT11 = 0 AND @COUNT21 = 0 AND @COUNT3 = 0 AND @COUNT4 = 0 AND @COUNT51 = 0 AND @COUNT52 = 0 AND @COUNT53 = 0 AND @COUNT54 = 0 AND @COUNT55 = 0
			AND @COUNT61 = 0 AND @COUNT62 = 0 AND @COUNT63 = 0 AND @COUNT64 = 0 AND @COUNT65 = 0 AND @COUNT66 = 0) BEGIN
			UPDATE KK_TBL_MEISHI_WK SET 
			KK_TBL_MEISHI_WK.AYITETANTOSHA_CD = NULL
			,KK_TBL_MEISHI_WK.ERROR_MSG = @ERR_MSG_KOKYAKU_NM_NAYI
			FROM KK_TBL_MEISHI_WK
			WHERE KK_TBL_MEISHI_WK.SESSION_ID = @SESSION_ID
			AND KK_TBL_MEISHI_WK.KAISHA_CD = @KAISHA_CD
			AND KK_TBL_MEISHI_WK.LINE_NO = @LINE_NO
			AND KK_TBL_MEISHI_WK.KOKYAKUKANRI_NO IS NULL
			AND KK_TBL_MEISHI_WK.ERROR_MSG IS NULL
		END
		
	FETCH NEXT FROM CUR_MEISHI
	INTO @LINE_NO	
		,@ERROR_MSG  
	END
	--カーソルを開放する
	CLOSE CUR_MEISHI
	DEALLOCATE CUR_MEISHI
	--マッチング処理END************************************************
	END TRY
    BEGIN CATCH
	SET @RetCd = 1;
    --終了処理
     GOTO END_PROC
    END CATCH

    RETURN @RetCd
    --END_PROCラベルの処理
	END_PROC:
    SELECT @RetCd
END
