IF EXISTS(SELECT * FROM sysobjects WHERE name='KK_MeishiDataToroku')
   DROP PROCEDURE dbo.KK_MeishiDataToroku
GO
CREATE PROC KK_MeishiDataToroku
@KAISHA_CD  NVARCHAR(15),                                              --会社コード
@USER_ID    NVARCHAR(30),                                              --ユーザID
@PGM_CD     NVARCHAR(30),                                              --プログラムコード
@SESSION_ID	NVARCHAR(50),											   --セッションID
@GET_ROW_FR		INT,
@GET_ROW_TO		INT
AS
BEGIN
	SET NOCOUNT ON;
	--INT変数リターンコード(@RetCd)を初期値0で定義。
	DECLARE @RetCd INT = 0
	DECLARE @NOW DATETIME = GETDATE()

	 DECLARE  @LINE_NO		DECIMAL(6)                                                                                 
     DECLARE  @KOKYAKUKANRI_NO	DECIMAL(10, 0)
	 DECLARE  @AITESAKI_TANTOSHA_CD	NVARCHAR(30) 
	 DECLARE  @AYITETANTOSHA_NM	NVARCHAR(40)
	 DECLARE  @KOKYAKU_NM	NVARCHAR(100)
	 DECLARE  @BUSHO_NM	NVARCHAR(50)
	 DECLARE  @YAKUSYOKU	NVARCHAR(50)
	 DECLARE  @ZIP_CD	NVARCHAR(8)
	 DECLARE  @JUSHO	NVARCHAR(100)
	 DECLARE  @TEL	NVARCHAR(20)
	 DECLARE  @FAX	NVARCHAR(20)
	 DECLARE  @EMAIL	NVARCHAR(100) 
	 DECLARE  @NAYIYOU	NVARCHAR(1000)                                                                       
     DECLARE  @TANTOSHA_CD	NVARCHAR(30) 
	 DECLARE  @SHUTOKU_DATE	NVARCHAR(30) 
	 DECLARE  @RIREKI_NO	DECIMAL(10)
	                            
     DECLARE  @WK_RIREKI_NO	DECIMAL(10, 0)
	 DECLARE @MOTO_RIREKI_NO	DECIMAL(10, 0)
	--名刺登録カーソル*********************************************
	DECLARE CUR_MEISHITOROKU CURSOR LOCAL FOR
	SELECT 
	   LINE_NO														--(付加情報)ファイル行番号
       ,KOKYAKUKANRI_NO                                             --顧客管理NO
	   ,AYITETANTOSHA_CD											--相手先担当者コード
	   ,AYITETANTOSHA_NM
	   ,KOKYAKU_NM
	   ,BUSHO_NM
	   ,YAKUSYOKU
	   ,ZIP_CD
	   ,JUSHO
	   ,TEL
	   ,FAX
	   ,EMAIL
	   ,NAYIYOU
	   ,TANTOSHA_CD													
	FROM
		KK_TBL_MEISHI_WK
	WHERE
		KK_TBL_MEISHI_WK.KAISHA_CD = @KAISHA_CD
		AND
		KK_TBL_MEISHI_WK.SESSION_ID = @SESSION_ID
	OPEN CUR_MEISHITOROKU		
	FETCH NEXT FROM CUR_MEISHITOROKU
		INTO @LINE_NO	
			,@KOKYAKUKANRI_NO
			,@AITESAKI_TANTOSHA_CD 
			,@AYITETANTOSHA_NM
			,@KOKYAKU_NM
			,@BUSHO_NM
			,@YAKUSYOKU
			,@ZIP_CD
			,@JUSHO
			,@TEL
			,@FAX
			,@EMAIL
			,@NAYIYOU
			,@TANTOSHA_CD	
	WHILE @@FETCH_STATUS = 0
	BEGIN	
		----**********相手先担当者コード採番START*****************************
		IF @AITESAKI_TANTOSHA_CD IS NULL OR @AITESAKI_TANTOSHA_CD = '' BEGIN
			DECLARE @SaibanRetCode INT
			DECLARE @wk_Prefix NVARCHAR(12) = ''
			DECLARE @keta DECIMAL(30)
			DECLARE @NewNo DECIMAL(10,0)
			DECLARE @NewNoE DECIMAL(10,0)

			DECLARE @RET_STATUS INTEGER = 0

			--担当者コードを採番する
			--採番ストアドを実行
			EXEC @SaibanRetCode = dbo.GET_NEXT_SAIBAN_WITH_LOCK
						@KAISHA_CD     = @KAISHA_CD				--会社コード
						,@SAIBAN_KBN   = 'ATNO'					--採番区分
						,@PREFIX       = '@NONPREFIX@' 			--プレフィックス
						,@SAIBAN_CNT   = 1						--採番数
						,@UPD_SHAIN_CD = @USER_ID				--更新社員コード
						,@UPD_PGM_CD   = @PGM_CD				--更新プログラムコード
						,@SAIBAN_KETA  = @keta OUTPUT			--採番桁数
						,@SAIBAN_NO_S  = @NewNo OUTPUT			--採番開始番号
						,@SAIBAN_NO_E  = @NewNoE OUTPUT			--採番終了番号
			IF (@SaibanRetCode <> 0)
			BEGIN
				SET @RET_STATUS = -2        --　-2:採番エラー
				GOTO END_PROC
			END

			SET @AITESAKI_TANTOSHA_CD = @NewNo
					UPDATE KK_TBL_MEISHI_WK SET
					KK_TBL_MEISHI_WK.AYITETANTOSHA_CD = @AITESAKI_TANTOSHA_CD
					WHERE KK_TBL_MEISHI_WK.LINE_NO = @LINE_NO
					AND KK_TBL_MEISHI_WK.SESSION_ID = @SESSION_ID
					AND KK_TBL_MEISHI_WK.KAISHA_CD = @KAISHA_CD

		--新規の場合KK_TBL_AITESAKI_TANTOSHAテーブルにKK_TBL_MEISHI_WKのデータをInsertする
		INSERT INTO KK_TBL_AITESAKI_TANTOSHA(KAISHA_CD,
											   KOKYAKUKANRI_NO,
											   AITESAKI_TANTOSHA_CD,
											   AITESAKI_TANTOSHA_NM,
											   KOKYAKU_NM,
											   AITESAKI_TANTO_BUSHO_NM,
											   YAKUSYOKU,
											   ZIP_CD,
											   TODOFUKEN,
											   JUSHO1,
											   JUSHO2,
											   TEL,
											   FAX,
											   MAIL,
											   MEMO,
											   KYOYU1,
											   KYOYU2,
											   MEISHI_KANRI_KOJIN_ID,
											   DEL_FLG,
											   INS_TM,
											   INS_SHAIN_CD,
											   INS_PGM_CD,
											   UPD_TM,
											   UPD_SHAIN_CD,
											   UPD_PGM_CD)
										SELECT @KAISHA_CD,
											   KK_TBL_MEISHI_WK.KOKYAKUKANRI_NO,
											   KK_TBL_MEISHI_WK.AYITETANTOSHA_CD,
											   KK_TBL_MEISHI_WK.AYITETANTOSHA_NM,
											   KK_TBL_MEISHI_WK.KOKYAKU_NM,
											   KK_TBL_MEISHI_WK.BUSHO_NM,
											   KK_TBL_MEISHI_WK.YAKUSYOKU,
											   REPLACE(KK_TBL_MEISHI_WK.ZIP_CD,'-',''),
											   ISNULL(TODOHUKEN.CD_NM,''),
											   SUBSTRING(KK_TBL_MEISHI_WK.JUSHO,LEN(ISNULL(TODOHUKEN.CD_NM,''))+1,100),
											   '',
											   KK_TBL_MEISHI_WK.TEL,
											   KK_TBL_MEISHI_WK.FAX,
											   KK_TBL_MEISHI_WK.EMAIL,
											   KK_TBL_MEISHI_WK.NAYIYOU,
											   '',
											   '',
											   '',
											   0,
											   @NOW,
											   @USER_ID,
											   @PGM_CD,
											   @NOW,
											   @USER_ID,
											   @PGM_CD
											   FROM KK_TBL_MEISHI_WK
											   LEFT JOIN BC_MST_CODE_KAISHA_BETU TODOHUKEN
													ON TODOHUKEN.KAISHA_CD = @KAISHA_CD
													AND	TODOHUKEN.CD_SECTION = '000038'--都道府県コード
													AND TODOHUKEN.DEL_FLG = 0
													AND KK_TBL_MEISHI_WK.JUSHO LIKE (TODOHUKEN.CD_NM + '%')
											   WHERE  KK_TBL_MEISHI_WK.SESSION_ID = @SESSION_ID
											   AND KK_TBL_MEISHI_WK.KAISHA_CD = @KAISHA_CD
											   AND KK_TBL_MEISHI_WK.LINE_NO = @LINE_NO			
		END
		----**********相手先担当者コード採番END*****************************
		--履歴NOクリア
		SET @MOTO_RIREKI_NO = 0
		SET @WK_RIREKI_NO = 0
		--**********履歴NO採番START*****************************
		SELECT 
		@KAISHA_CD = KAISHA_CD,
		@SESSION_ID = SESSION_ID,
		@WK_RIREKI_NO = RIREKI_NO
		FROM
		(
		SELECT 
			KAISHA_CD,
			SESSION_ID,
			KOKYAKUKANRI_NO,
			AYITETANTOSHA_CD,
			RIREKI_NO,
			ROW_NUMBER() OVER (ORDER BY RIREKI_NO DESC ) rid
		FROM KK_TBL_MEISHI_WK
		WHERE KK_TBL_MEISHI_WK.SESSION_ID = @SESSION_ID
			 AND KK_TBL_MEISHI_WK.KAISHA_CD = @KAISHA_CD
			 AND KK_TBL_MEISHI_WK.AYITETANTOSHA_CD = @AITESAKI_TANTOSHA_CD
			 AND KK_TBL_MEISHI_WK.KOKYAKUKANRI_NO = @KOKYAKUKANRI_NO
		)AS WK
		WHERE WK.KAISHA_CD = @KAISHA_CD
			AND WK.SESSION_ID = @SESSION_ID
			AND WK.AYITETANTOSHA_CD = @AITESAKI_TANTOSHA_CD
			AND WK.KOKYAKUKANRI_NO = @KOKYAKUKANRI_NO
			AND WK.rid = 1
		
		SELECT
			@KAISHA_CD = KAISHA_CD,
			@MOTO_RIREKI_NO = RIREKI_NO
		FROM
		(SELECT
			KAISHA_CD,
			KOKYAKUKANRI_NO,
			AITESAKI_TANTOSHA_CD,
			RIREKI_NO,
			ROW_NUMBER() OVER (ORDER BY RIREKI_NO DESC ) rid
		FROM KK_TBL_MEISHI_KOKAN_RIREKI MEISHI
		WHERE	MEISHI.KAISHA_CD = @KAISHA_CD
			AND MEISHI.KOKYAKUKANRI_NO = @KOKYAKUKANRI_NO
			AND MEISHI.AITESAKI_TANTOSHA_CD = @AITESAKI_TANTOSHA_CD
		) AS EMISHI1
		WHERE EMISHI1.KAISHA_CD = @KAISHA_CD
			AND EMISHI1.KOKYAKUKANRI_NO = @KOKYAKUKANRI_NO
			AND EMISHI1.AITESAKI_TANTOSHA_CD = @AITESAKI_TANTOSHA_CD
			AND EMISHI1.rid = 1	

		IF @MOTO_RIREKI_NO IS NULL BEGIN
			SET @MOTO_RIREKI_NO = 0
		END
		IF @WK_RIREKI_NO IS NULL BEGIN
			SET @WK_RIREKI_NO = 0
		END
		IF @MOTO_RIREKI_NO > @WK_RIREKI_NO BEGIN
			UPDATE KK_TBL_MEISHI_WK SET 
			KK_TBL_MEISHI_WK.RIREKI_NO = @MOTO_RIREKI_NO + 1
			WHERE KK_TBL_MEISHI_WK.KAISHA_CD = @KAISHA_CD
			AND  KK_TBL_MEISHI_WK.SESSION_ID = @SESSION_ID
			AND  KK_TBL_MEISHI_WK.LINE_NO = @LINE_NO
		END
		ELSE 
			UPDATE KK_TBL_MEISHI_WK SET 
			KK_TBL_MEISHI_WK.RIREKI_NO = @WK_RIREKI_NO + 1
			WHERE KK_TBL_MEISHI_WK.KAISHA_CD = @KAISHA_CD
			AND  KK_TBL_MEISHI_WK.SESSION_ID = @SESSION_ID
			AND  KK_TBL_MEISHI_WK.LINE_NO = @LINE_NO		 				 
		--**********履歴NO採番END*****************************	

		FETCH NEXT FROM CUR_MEISHITOROKU
		INTO @LINE_NO	
			,@KOKYAKUKANRI_NO
			,@AITESAKI_TANTOSHA_CD 
			,@AYITETANTOSHA_NM
			,@KOKYAKU_NM
			,@BUSHO_NM
			,@YAKUSYOKU
			,@ZIP_CD
			,@JUSHO
			,@TEL
			,@FAX
			,@EMAIL
			,@NAYIYOU
			,@TANTOSHA_CD	
		END
		--カーソルをクローズ
		CLOSE CUR_MEISHITOROKU
		DEALLOCATE CUR_MEISHITOROKU
		--担当部署の設定*************************************************
		UPDATE KK_TBL_MEISHI_WK SET 
		KK_TBL_MEISHI_WK.TANTO_BUSHO_CD = BUSHO.BUSHO_CD 
		FROM KK_TBL_MEISHI_WK
		INNER JOIN BC_MST_SHAIN MSH ON
			MSH.KAISHA_CD = KK_TBL_MEISHI_WK.KAISHA_CD
			AND
			MSH.SHAIN_CD = KK_TBL_MEISHI_WK.TANTOSHA_CD
		LEFT JOIN BC_MST_SHOZOKU shozoku
			ON shozoku.KAISHA_CD = KK_TBL_MEISHI_WK.KAISHA_CD
			AND shozoku.SHAIN_CD = KK_TBL_MEISHI_WK.TANTOSHA_CD
		INNER JOIN
			(
				SELECT
					 KAISHA_CD
					,SHAIN_CD
					,MIN(SHOZOKU_START_YMD) AS SHOZOKU_START_YMD
				FROM
					BC_MST_SHOZOKU
				WHERE
					DEL_FLG = 0
					AND DATEDIFF(dd, GETDATE(), SHOZOKU_END_YMD)>=0
				GROUP BY KAISHA_CD, SHAIN_CD
			) shozoku_filter
			ON shozoku.KAISHA_CD = shozoku_filter.KAISHA_CD
			AND shozoku.SHAIN_CD = shozoku_filter.SHAIN_CD
			AND shozoku.SHOZOKU_START_YMD = shozoku_filter.SHOZOKU_START_YMD
		LEFT JOIN BC_MST_BUSHO BUSHO
			ON BUSHO.KAISHA_CD = shozoku.KAISHA_CD
			AND BUSHO.BUSHO_CD = shozoku.BUSHO_CD
			AND DATEDIFF(dd, BUSHO.START_YMD, shozoku.SHOZOKU_START_YMD)>=0
			AND DATEDIFF(dd, shozoku.SHOZOKU_START_YMD, BUSHO.END_YMD)>=0
			AND BUSHO.DEL_FLG = 0
		WHERE KK_TBL_MEISHI_WK.KAISHA_CD = @KAISHA_CD
				AND	KK_TBL_MEISHI_WK.SESSION_ID = @SESSION_ID

		--KK_TBL_MEISHI_KOKAN_RIREKIテーブルにKK_TBL_MEISHI_WKのデータをInsertする
		INSERT INTO KK_TBL_MEISHI_KOKAN_RIREKI(KAISHA_CD,
											   KOKYAKUKANRI_NO,
											   AITESAKI_TANTOSHA_CD,
											   RIREKI_NO,
											   SHUTOKU_DATE,
											   AITESAKI_TANTOSHA_NM,
											   KOKYAKU_NM,
											   AITESAKI_TANTO_BUSHO_NM,
											   YAKUSYOKU,
											   ZIP_CD,
											   TODOFUKEN,
											   JUSHO1,
											   JUSHO2,
											   TEL,
											   FAX,
											   MAIL,
											   MEMO,
											   TANTO_BUSHO_CD,
											   TANTOSHA_CD,
											   DEL_FLG,
											   INS_TM,
											   INS_SHAIN_CD,
											   INS_PGM_CD,
											   UPD_TM,
											   UPD_SHAIN_CD,
											   UPD_PGM_CD)
										SELECT @KAISHA_CD,
											   KK_TBL_MEISHI_WK.KOKYAKUKANRI_NO,
											   KK_TBL_MEISHI_WK.AYITETANTOSHA_CD,
											   KK_TBL_MEISHI_WK.RIREKI_NO,
											   KK_TBL_MEISHI_WK.SHUTOKU_DATE,
											   KK_TBL_MEISHI_WK.AYITETANTOSHA_NM,
											   KK_TBL_MEISHI_WK.KOKYAKU_NM,
											   KK_TBL_MEISHI_WK.BUSHO_NM,
											   KK_TBL_MEISHI_WK.YAKUSYOKU,
											   REPLACE(KK_TBL_MEISHI_WK.ZIP_CD,'-',''),
											   ISNULL(TODOHUKEN.CD_NM,''),
											   SUBSTRING(KK_TBL_MEISHI_WK.JUSHO,LEN(ISNULL(TODOHUKEN.CD_NM,''))+1,100),
											   '',
											   KK_TBL_MEISHI_WK.TEL,
											   KK_TBL_MEISHI_WK.FAX,
											   KK_TBL_MEISHI_WK.EMAIL,
											   KK_TBL_MEISHI_WK.NAYIYOU,
											   KK_TBL_MEISHI_WK.TANTO_BUSHO_CD,
											   KK_TBL_MEISHI_WK.TANTOSHA_CD,
											   0,
											   @NOW,
											   @USER_ID,
											   @PGM_CD,
											   @NOW,
											   @USER_ID,
											   @PGM_CD
											   FROM KK_TBL_MEISHI_WK 
											   LEFT JOIN BC_MST_CODE_KAISHA_BETU TODOHUKEN
													ON TODOHUKEN.KAISHA_CD = @KAISHA_CD
													AND	TODOHUKEN.CD_SECTION = '000038'--都道府県コード
													AND TODOHUKEN.DEL_FLG = 0
													AND KK_TBL_MEISHI_WK.JUSHO LIKE (TODOHUKEN.CD_NM + '%')
											   WHERE  KK_TBL_MEISHI_WK.SESSION_ID = @SESSION_ID
											   AND KK_TBL_MEISHI_WK.KAISHA_CD = @KAISHA_CD

			--***結果一覧で相手先担当者の指定がされている場合、最新情報で相手先担当者マスタを更新
			--SHUTOKU_DATEを降順ソートし、重複するデータがある場合はRIREKI_NOが大きいものを更新
			DECLARE CUR_AYITE CURSOR LOCAL FOR			

			SELECT WK.KOKYAKUKANRI_NO,
				   WK.AYITETANTOSHA_CD	,
				   MAX (CONVERT(DATE ,WK.SHUTOKU_DATE,111))
			FROM KK_TBL_AITESAKI_TANTOSHA AITE
			LEFT JOIN KK_TBL_MEISHI_WK WK ON
			WK.KAISHA_CD = AITE.KAISHA_CD
				AND WK.KOKYAKUKANRI_NO = AITE.KOKYAKUKANRI_NO
				AND WK.AYITETANTOSHA_CD = AITE.AITESAKI_TANTOSHA_CD
			WHERE AITE.KAISHA_CD = @KAISHA_CD
				AND WK.SESSION_ID = @SESSION_ID
				AND WK.KAISHA_CD = @KAISHA_CD									
			GROUP BY WK.KOKYAKUKANRI_NO,	
					WK.AYITETANTOSHA_CD	

			OPEN CUR_AYITE		
			FETCH NEXT FROM CUR_AYITE
			INTO @KOKYAKUKANRI_NO
				,@AITESAKI_TANTOSHA_CD
				,@SHUTOKU_DATE 			
			WHILE @@FETCH_STATUS = 0
			BEGIN	
				SELECT 
				    @RIREKI_NO =  MAX(WK.RIREKI_NO)
				FROM KK_TBL_AITESAKI_TANTOSHA AITE
				LEFT JOIN KK_TBL_MEISHI_WK WK ON
				WK.KAISHA_CD = AITE.KAISHA_CD
					AND WK.KOKYAKUKANRI_NO = AITE.KOKYAKUKANRI_NO
					AND WK.AYITETANTOSHA_CD = AITE.AITESAKI_TANTOSHA_CD
				WHERE AITE.KAISHA_CD = @KAISHA_CD
					AND WK.SESSION_ID = @SESSION_ID
					AND WK.KAISHA_CD = @KAISHA_CD
					AND AITE.KOKYAKUKANRI_NO = @KOKYAKUKANRI_NO	
					AND AITE.AITESAKI_TANTOSHA_CD = @AITESAKI_TANTOSHA_CD
					AND (CONVERT(DATE ,WK.SHUTOKU_DATE,111)) = (CONVERT(DATE ,@SHUTOKU_DATE,111))							
				GROUP BY WK.KOKYAKUKANRI_NO,	
						WK.AYITETANTOSHA_CD,
						WK.SHUTOKU_DATE

					UPDATE  KK_TBL_AITESAKI_TANTOSHA SET
						AITESAKI_TANTOSHA_NM = WK.AYITETANTOSHA_NM
						,KOKYAKU_NM = WK.KOKYAKU_NM
						,AITESAKI_TANTO_BUSHO_NM = WK.BUSHO_NM
						,YAKUSYOKU = WK.YAKUSYOKU
						,ZIP_CD = REPLACE(WK.ZIP_CD,'-','')
						,JUSHO1 = SUBSTRING(WK.JUSHO,LEN(ISNULL(TODOHUKEN.CD_NM,''))+1,100)
						,TEL = WK.TEL
						,FAX = WK.FAX
						,MAIL = WK.EMAIL
						,MEMO = WK.NAYIYOU
						,UPD_TM = @NOW
						,UPD_SHAIN_CD = @USER_ID
						,UPD_PGM_CD = @PGM_CD
					FROM KK_TBL_AITESAKI_TANTOSHA AITE
					LEFT JOIN KK_TBL_MEISHI_WK WK ON
						WK.KAISHA_CD = AITE.KAISHA_CD
						AND
						WK.KOKYAKUKANRI_NO = AITE.KOKYAKUKANRI_NO
						AND WK.AYITETANTOSHA_CD = AITE.AITESAKI_TANTOSHA_CD
					LEFT JOIN BC_MST_CODE_KAISHA_BETU TODOHUKEN
						ON TODOHUKEN.KAISHA_CD = @KAISHA_CD
						AND	TODOHUKEN.CD_SECTION = '000038'--都道府県コード
						AND TODOHUKEN.DEL_FLG = 0
						AND WK.JUSHO LIKE (TODOHUKEN.CD_NM + '%')
					WHERE AITE.KAISHA_CD = @KAISHA_CD
						AND AITE.KOKYAKUKANRI_NO = @KOKYAKUKANRI_NO
						AND AITE.AITESAKI_TANTOSHA_CD = @AITESAKI_TANTOSHA_CD
						AND WK.SESSION_ID = @SESSION_ID
						AND WK.KAISHA_CD = @KAISHA_CD
						AND (CONVERT(DATE ,WK.SHUTOKU_DATE,111)) =(CONVERT(DATE ,@SHUTOKU_DATE,111))		
						AND WK.RIREKI_NO = @RIREKI_NO		
						AND (@AITESAKI_TANTOSHA_CD IS NOT NULL OR @AITESAKI_TANTOSHA_CD <>'')
		FETCH NEXT FROM CUR_AYITE
		INTO @KOKYAKUKANRI_NO
			,@AITESAKI_TANTOSHA_CD 
			,@SHUTOKU_DATE 
		END
		--カーソルをクローズ
		CLOSE CUR_AYITE 
		DEALLOCATE CUR_AYITE
		--*******相手先担当者マスタを更新 END
		--エラークリア
		UPDATE KK_TBL_MEISHI_WK
		SET
		KK_TBL_MEISHI_WK.ERROR_MSG = NULL   		   
		WHERE  KK_TBL_MEISHI_WK.SESSION_ID = @SESSION_ID
		 AND KK_TBL_MEISHI_WK.KAISHA_CD = @KAISHA_CD

	IF (@RetCd = 0) BEGIN
	    --変数リターンコード(@RetCd)を抽出する。
   		SELECT @RetCd
    --KK_TBL_MEISHI_WKを下記条件で抽出する
    	SELECT     		
    		LINE_NO,
			KOKYAKUKANRI_NO,
			AYITETANTOSHA_CD,			
			KOKYAKU_NM,
			AYITETANTOSHA_NM,
			ERROR_MSG		
        FROM (
			SELECT LINE_NO,
			AYITETANTOSHA_CD,
			KOKYAKUKANRI_NO,
			AYITETANTOSHA_NM,
			KOKYAKU_NM,
			ERROR_MSG,
			SESSION_ID,
			ROW_NUMBER() OVER ( ORDER BY LINE_NO ) AS row_num
		FROM KK_TBL_MEISHI_WK
		WHERE SESSION_ID = @SESSION_ID
		 AND KAISHA_CD = @KAISHA_CD

		) as t
		WHERE
		  t.row_num BETWEEN @GET_ROW_FR AND @GET_ROW_TO
		  AND t.SESSION_ID = @SESSION_ID
		ORDER BY
           LINE_NO ASC
               
		SELECT     		
		COUNT(*)
		FROM KK_TBL_MEISHI_WK
		WHERE KK_TBL_MEISHI_WK.SESSION_ID = @SESSION_ID
		 AND KK_TBL_MEISHI_WK.KAISHA_CD = @KAISHA_CD
		END

	END_PROC:
    --変数リターンコード(@RetCd)を抽出する。
   	SELECT @RetCd
END
