IF EXISTS(SELECT * FROM sysobjects WHERE name='KK_MeishiWKUpdata')
   DROP PROCEDURE dbo.KK_MeishiWKUpdata
GO
CREATE PROC KK_MeishiWKUpdata
@KAISHA_CD  NVARCHAR(15),                                              --会社コード
@USER_ID    NVARCHAR(30),                                              --ユーザID
@PGM_CD     NVARCHAR(30),                                              --プログラムコード
@SESSION_ID	NVARCHAR(50),											   --セッションID
@AYITETANTOSHA_CD1  NVARCHAR(30),									   --相手先担当者
@KOKYAKUKANRI_NO1 DECIMAL(10,0),										   --顧客名
@AYITETANTOSHA_CD2  NVARCHAR(30),									   --相手先担当者
@KOKYAKUKANRI_NO2 DECIMAL(10,0),										   --顧客名
@AYITETANTOSHA_CD3  NVARCHAR(30),									   --相手先担当者
@KOKYAKUKANRI_NO3 DECIMAL(10,0),										   --顧客名
@AYITETANTOSHA_CD4  NVARCHAR(30),									   --相手先担当者
@KOKYAKUKANRI_NO4 DECIMAL(10,0),										   --顧客名
@AYITETANTOSHA_CD5  NVARCHAR(30),									   --相手先担当者
@KOKYAKUKANRI_NO5 DECIMAL(10,0),										   --顧客名
@AYITETANTOSHA_CD6  NVARCHAR(30),									   --相手先担当者
@KOKYAKUKANRI_NO6 DECIMAL(10,0),										   --顧客名
@AYITETANTOSHA_CD7  NVARCHAR(30),									   --相手先担当者
@KOKYAKUKANRI_NO7 DECIMAL(10,0),										   --顧客名
@AYITETANTOSHA_CD8  NVARCHAR(30),									   --相手先担当者
@KOKYAKUKANRI_NO8 DECIMAL(10,0),										   --顧客名
@AYITETANTOSHA_CD9  NVARCHAR(30),									   --相手先担当者
@KOKYAKUKANRI_NO9 DECIMAL(10,0),										   --顧客名
@AYITETANTOSHA_CD10  NVARCHAR(30),									   --相手先担当者
@KOKYAKUKANRI_NO10 DECIMAL(10,0),									   --顧客名
@ROW_NO_NOW_FR 		INT,												   --現在画面RowNoFr
@ROW_NO_NOW_TO 		INT,												   --現在画面RowNoTo
@GET_ROW_FR		INT,
@GET_ROW_TO		INT
AS
BEGIN
    --INT変数リターンコード(@RetCd)を初期値0で定義。
    DECLARE @RetCd INT = 0
    --現在日時を変数
    DECLARE @NOW DATETIME = GETDATE()
	
	--該当pageデータの更新 次のpage取得
	IF (@AYITETANTOSHA_CD1 IS NOT NULL AND @AYITETANTOSHA_CD1 <> '') OR (@KOKYAKUKANRI_NO1 IS NOT NULL)   AND @ROW_NO_NOW_FR <= @ROW_NO_NOW_TO BEGIN
	UPDATE KK_TBL_MEISHI_WK
	    SET 
		KK_TBL_MEISHI_WK.AYITETANTOSHA_CD = @AYITETANTOSHA_CD1,
		KK_TBL_MEISHI_WK.KOKYAKUKANRI_NO = @KOKYAKUKANRI_NO1,
		KK_TBL_MEISHI_WK.UPD_PGM_CD = @PGM_CD,
		KK_TBL_MEISHI_WK.UPD_SHAIN_CD = @USER_ID,
		KK_TBL_MEISHI_WK.UPD_TM = @NOW
	   WHERE KK_TBL_MEISHI_WK.LINE_NO  = @ROW_NO_NOW_FR
	   AND KK_TBL_MEISHI_WK.SESSION_ID = @SESSION_ID
	END
	IF (@AYITETANTOSHA_CD2 IS NOT NULL AND @AYITETANTOSHA_CD2 <> '') OR (@KOKYAKUKANRI_NO2 IS NOT NULL) AND (@ROW_NO_NOW_FR + 1) <= @ROW_NO_NOW_TO BEGIN
	UPDATE KK_TBL_MEISHI_WK
	    SET 
		KK_TBL_MEISHI_WK.AYITETANTOSHA_CD = @AYITETANTOSHA_CD2,
		KK_TBL_MEISHI_WK.KOKYAKUKANRI_NO = @KOKYAKUKANRI_NO2,
		KK_TBL_MEISHI_WK.UPD_PGM_CD = @PGM_CD,
		KK_TBL_MEISHI_WK.UPD_SHAIN_CD = @USER_ID,
		KK_TBL_MEISHI_WK.UPD_TM = @NOW
	   WHERE KK_TBL_MEISHI_WK.LINE_NO  = @ROW_NO_NOW_FR + 1
			AND KK_TBL_MEISHI_WK.SESSION_ID = @SESSION_ID
	END
	IF (@AYITETANTOSHA_CD3 IS NOT NULL AND @AYITETANTOSHA_CD3 <> '') OR (@KOKYAKUKANRI_NO3 IS NOT NULL) AND (@ROW_NO_NOW_FR + 2) <= @ROW_NO_NOW_TO BEGIN
	UPDATE KK_TBL_MEISHI_WK
		SET 
		KK_TBL_MEISHI_WK.AYITETANTOSHA_CD = @AYITETANTOSHA_CD3,
		KK_TBL_MEISHI_WK.KOKYAKUKANRI_NO = @KOKYAKUKANRI_NO3,
		KK_TBL_MEISHI_WK.UPD_PGM_CD = @PGM_CD,
		KK_TBL_MEISHI_WK.UPD_SHAIN_CD = @USER_ID,
		KK_TBL_MEISHI_WK.UPD_TM = @NOW
	   WHERE KK_TBL_MEISHI_WK.LINE_NO  = @ROW_NO_NOW_FR + 2
			AND KK_TBL_MEISHI_WK.SESSION_ID = @SESSION_ID
	END
	IF (@AYITETANTOSHA_CD4 IS NOT NULL AND @AYITETANTOSHA_CD4 <> '') OR (@KOKYAKUKANRI_NO4 IS NOT NULL) AND (@ROW_NO_NOW_FR + 3) <= @ROW_NO_NOW_TO BEGIN
	UPDATE KK_TBL_MEISHI_WK
	    SET 
		KK_TBL_MEISHI_WK.AYITETANTOSHA_CD = @AYITETANTOSHA_CD4,
		KK_TBL_MEISHI_WK.KOKYAKUKANRI_NO = @KOKYAKUKANRI_NO4,
		KK_TBL_MEISHI_WK.UPD_PGM_CD = @PGM_CD,
		KK_TBL_MEISHI_WK.UPD_SHAIN_CD = @USER_ID,
		KK_TBL_MEISHI_WK.UPD_TM = @NOW
	   WHERE KK_TBL_MEISHI_WK.LINE_NO  = @ROW_NO_NOW_FR + 3
			AND KK_TBL_MEISHI_WK.SESSION_ID = @SESSION_ID
	END
	IF (@AYITETANTOSHA_CD5 IS NOT NULL AND @AYITETANTOSHA_CD5 <> '') OR (@KOKYAKUKANRI_NO5 IS NOT NULL) AND (@ROW_NO_NOW_FR + 4) <= @ROW_NO_NOW_TO BEGIN
	UPDATE KK_TBL_MEISHI_WK
	    SET 
		KK_TBL_MEISHI_WK.AYITETANTOSHA_CD = @AYITETANTOSHA_CD5,
		KK_TBL_MEISHI_WK.KOKYAKUKANRI_NO = @KOKYAKUKANRI_NO5,
		KK_TBL_MEISHI_WK.UPD_PGM_CD = @PGM_CD,
		KK_TBL_MEISHI_WK.UPD_SHAIN_CD = @USER_ID,
		KK_TBL_MEISHI_WK.UPD_TM = @NOW
		   WHERE KK_TBL_MEISHI_WK.LINE_NO  = @ROW_NO_NOW_FR + 4
				AND KK_TBL_MEISHI_WK.SESSION_ID = @SESSION_ID
		END
		IF (@AYITETANTOSHA_CD6 IS NOT NULL AND @AYITETANTOSHA_CD6 <> '') OR (@KOKYAKUKANRI_NO6 IS NOT NULL)AND (@ROW_NO_NOW_FR + 5) <= @ROW_NO_NOW_TO BEGIN
		UPDATE KK_TBL_MEISHI_WK
		    SET 
		KK_TBL_MEISHI_WK.AYITETANTOSHA_CD = @AYITETANTOSHA_CD6,
		KK_TBL_MEISHI_WK.KOKYAKUKANRI_NO = @KOKYAKUKANRI_NO6,
		KK_TBL_MEISHI_WK.UPD_PGM_CD = @PGM_CD,
		KK_TBL_MEISHI_WK.UPD_SHAIN_CD = @USER_ID,
		KK_TBL_MEISHI_WK.UPD_TM = @NOW
		WHERE KK_TBL_MEISHI_WK.LINE_NO  = @ROW_NO_NOW_FR + 5
				AND KK_TBL_MEISHI_WK.SESSION_ID = @SESSION_ID
		END
		IF (@AYITETANTOSHA_CD7 IS NOT NULL AND @AYITETANTOSHA_CD7 <> '') OR (@KOKYAKUKANRI_NO7 IS NOT NULL) AND (@ROW_NO_NOW_FR + 6) <= @ROW_NO_NOW_TO BEGIN
		UPDATE KK_TBL_MEISHI_WK
		    SET 
		KK_TBL_MEISHI_WK.AYITETANTOSHA_CD = @AYITETANTOSHA_CD7,
		KK_TBL_MEISHI_WK.KOKYAKUKANRI_NO = @KOKYAKUKANRI_NO7,
		KK_TBL_MEISHI_WK.UPD_PGM_CD = @PGM_CD,
		KK_TBL_MEISHI_WK.UPD_SHAIN_CD = @USER_ID,
		KK_TBL_MEISHI_WK.UPD_TM = @NOW
	   WHERE KK_TBL_MEISHI_WK.LINE_NO  = @ROW_NO_NOW_FR + 6
			AND KK_TBL_MEISHI_WK.SESSION_ID = @SESSION_ID
	END
	IF (@AYITETANTOSHA_CD8 IS NOT NULL AND @AYITETANTOSHA_CD8 <> '') OR (@KOKYAKUKANRI_NO8 IS NOT NULL) AND (@ROW_NO_NOW_FR + 7) <= @ROW_NO_NOW_TO  BEGIN
	UPDATE KK_TBL_MEISHI_WK
	    SET 
		KK_TBL_MEISHI_WK.AYITETANTOSHA_CD = @AYITETANTOSHA_CD8,
		KK_TBL_MEISHI_WK.KOKYAKUKANRI_NO = @KOKYAKUKANRI_NO8,
		KK_TBL_MEISHI_WK.UPD_PGM_CD = @PGM_CD,
		KK_TBL_MEISHI_WK.UPD_SHAIN_CD = @USER_ID,
		KK_TBL_MEISHI_WK.UPD_TM = @NOW
	   WHERE KK_TBL_MEISHI_WK.LINE_NO  = @ROW_NO_NOW_FR + 7
			AND KK_TBL_MEISHI_WK.SESSION_ID = @SESSION_ID
	END
	IF (@AYITETANTOSHA_CD9 IS NOT NULL AND @AYITETANTOSHA_CD9 <> '') OR (@KOKYAKUKANRI_NO9 IS NOT NULL) AND (@ROW_NO_NOW_FR + 8) <= @ROW_NO_NOW_TO BEGIN
	UPDATE KK_TBL_MEISHI_WK
	    SET 
		KK_TBL_MEISHI_WK.AYITETANTOSHA_CD = @AYITETANTOSHA_CD9,
		KK_TBL_MEISHI_WK.KOKYAKUKANRI_NO = @KOKYAKUKANRI_NO9,
		KK_TBL_MEISHI_WK.UPD_PGM_CD = @PGM_CD,
		KK_TBL_MEISHI_WK.UPD_SHAIN_CD = @USER_ID,
		KK_TBL_MEISHI_WK.UPD_TM = @NOW
	   WHERE KK_TBL_MEISHI_WK.LINE_NO  = @ROW_NO_NOW_FR + 8
			AND KK_TBL_MEISHI_WK.SESSION_ID = @SESSION_ID
	END
	IF (@AYITETANTOSHA_CD10 IS NOT NULL AND @AYITETANTOSHA_CD10 <> '') OR (@KOKYAKUKANRI_NO10 IS NOT NULL)AND (@ROW_NO_NOW_FR + 9) <= @ROW_NO_NOW_TO BEGIN
	UPDATE KK_TBL_MEISHI_WK
	    SET 
		KK_TBL_MEISHI_WK.AYITETANTOSHA_CD = @AYITETANTOSHA_CD10,
		KK_TBL_MEISHI_WK.KOKYAKUKANRI_NO = @KOKYAKUKANRI_NO10,
		KK_TBL_MEISHI_WK.UPD_PGM_CD = @PGM_CD,
		KK_TBL_MEISHI_WK.UPD_SHAIN_CD = @USER_ID,
		KK_TBL_MEISHI_WK.UPD_TM = @NOW
	   WHERE KK_TBL_MEISHI_WK.LINE_NO  = @ROW_NO_NOW_FR + 9
			AND KK_TBL_MEISHI_WK.SESSION_ID = @SESSION_ID
	END

	UPDATE KK_TBL_MEISHI_WK
    SET    
	KK_TBL_MEISHI_WK.KOKYAKUKANRI_NO = NULL
	WHERE KK_TBL_MEISHI_WK.KOKYAKUKANRI_NO = 0
	AND  KK_TBL_MEISHI_WK.SESSION_ID = @SESSION_ID
	AND  KK_TBL_MEISHI_WK.KAISHA_CD = @KAISHA_CD
    --KK_TBL_MEISHI_WKを下記条件で抽出する
    		SELECT     		
    		LINE_NO,
			KOKYAKUKANRI_NO,
			AYITETANTOSHA_CD,			
			KOKYAKU_NM,
			AYITETANTOSHA_NM,
			ERROR_MSG		
        FROM (
			SELECT LINE_NO,
			AYITETANTOSHA_CD,
			KOKYAKUKANRI_NO,
			AYITETANTOSHA_NM,
			KOKYAKU_NM,
			ERROR_MSG,
			SESSION_ID,
			ROW_NUMBER() OVER ( ORDER BY LINE_NO ) AS row_num
		FROM KK_TBL_MEISHI_WK
		WHERE SESSION_ID = @SESSION_ID
		) as t
		WHERE
		  t.row_num BETWEEN @GET_ROW_FR AND @GET_ROW_TO
		  AND t.SESSION_ID = @SESSION_ID
		ORDER BY
           LINE_NO ASC
		            
		SELECT     		
		 COUNT(*)
		FROM KK_TBL_MEISHI_WK
		WHERE KK_TBL_MEISHI_WK.SESSION_ID = @SESSION_ID
    --END_PROCラベルの処理
END_PROC:
    SELECT @RetCd
END
